import { cache } from "react";

import type { FileRef, Money, PaginatedResponse } from "@repo/shared/types";

// Reads of the public products API, for a client with no signed-in user.
//
// Generated by grit with --public, and not overwritten when the resource is
// regenerated: the Go side's allowlist is yours to edit, and this file is typed
// against it.
//
// These call /public/products, not the authenticated routes the hooks in
// hooks/use-products.ts call. The authenticated ones answer 401
// without a session, which is correct for the admin panel and useless here.

const API_URL = (
  process.env.API_INTERNAL_URL ||
  process.env.NEXT_PUBLIC_API_URL ||
  "http://localhost:8080"
).replace(/\/+$/, "");

// Publishable by design: it reaches the read-only public endpoints and nothing
// else, which is why the seeder writes it as NEXT_PUBLIC_.
const API_KEY = process.env.NEXT_PUBLIC_API_KEY ?? "";

// Pages revalidate on this interval, so an edit in the admin shows within a
// minute without a deploy.
const REVALIDATE_SECONDS = 60;

// PublicProduct is the published shape: the allowlist in
// internal/handlers/product_public.go, not the model. Add a field
// there and add it here.
export interface PublicProduct {
  id: string;
  collection_id: string;
  title: string;
  handle: string;
  description: string;
  price: Money;
  featured_image: FileRef | null;
  images: FileRef[];
  available: boolean;
}

export type PublicProductPage = {
  data: PublicProduct[];
  meta: PaginatedResponse<PublicProduct>["meta"] | undefined;
};

async function publicGet<T>(path: string): Promise<{ status: number; body: T | null }> {
  try {
    const res = await fetch(API_URL + path, {
      headers: API_KEY ? { "X-API-Key": API_KEY } : {},
      next: { revalidate: REVALIDATE_SECONDS },
    });
    if (!res.ok) return { status: res.status, body: null };
    return { status: res.status, body: (await res.json()) as T };
  } catch {
    // The API is unreachable, as it is while a production build runs in CI. A
    // list renders empty and fills in on the next request rather than failing
    // the build.
    return { status: 0, body: null };
  }
}

// One page of products. Every search, sort, filter and range the
// public handler allows is a query parameter; anything it does not allow is
// ignored rather than rejected.
export const getPublicProducts = cache(async (
  params: Record<string, string | number | undefined> = {}
): Promise<PublicProductPage> => {
  const query = new URLSearchParams();
  for (const [key, value] of Object.entries(params)) {
    if (value !== undefined && value !== "") query.set(key, String(value));
  }
  const suffix = query.toString() ? "?" + query.toString() : "";
  const { body } = await publicGet<PaginatedResponse<PublicProduct>>("/api/v1/public/products" + suffix);
  return { data: body?.data ?? [], meta: body?.meta };
});

// One product by its public key, or null when there is none.
//
// A row that is archived or switched off is a 404 here, the same as one that
// never existed: whether it exists is itself not public. An API that fails is
// an error rather than a missing row, so it is not reported as null.
export const getPublicProduct = cache(async (key: string): Promise<PublicProduct | null> => {
  const { status, body } = await publicGet<{ data: PublicProduct }>(
    "/api/v1/public/products/" + encodeURIComponent(key)
  );
  if (status === 404) return null;
  if (!body) throw new Error("the public product API answered " + (status || "nothing") + " for " + key);
  return body.data;
});

// The "similar items" strip on a detail page. The server caps the limit, so
// asking for more than it allows returns what it allows.
export const getRelatedProducts = cache(async (
  key: string,
  limit = 8
): Promise<PublicProduct[]> => {
  const { body } = await publicGet<{ data: PublicProduct[] }>(
    "/api/v1/public/products/" + encodeURIComponent(key) + "/related?limit=" + limit
  );
  return body?.data ?? [];
});
