import Link from 'next/link'
import { ArrowRight, ArrowLeft } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { SiteHeader } from '@/components/site-header'
import { DocsSidebar } from '@/components/docs-sidebar'
import { CodeBlock } from '@/components/code-block'
import { getDocMetadata } from '@/config/docs-metadata'

// Generated by scripts/tier-tutorials.py. Edit the table there, not this file.

export const metadata = getDocMetadata('/docs/tutorials/contacts/single')

export default function ContactsSingleTutorialPage() {
  return (
    <div className="min-h-screen bg-background isolate">
      <SiteHeader />
      <DocsSidebar />

      <main className="lg:pl-64">
        <div className="container max-w-screen-xl py-10 px-6">
          <div className="max-w-3xl">
            <div className="mb-10">
              <span className="tag-mono text-primary/80 mb-3 block">Tutorial</span>
              <h1 className="text-4xl font-bold tracking-tight mb-4">Contacts: one binary</h1>
              <p className="text-lg text-muted-foreground leading-relaxed">One folder that looks like the web project it is, with the Go API in <code>api/</code> beside it. The frontend is a Vite app with the admin panel at <code>/admin</code>, and the build puts it inside the binary: what you deploy is a single file with no runtime to install next to it.</p>
            </div>

            <div className="prose-grit">
              <p>
                The app is a contact book: contacts that belong to groups, each with a photo. Two
                resources, two commands, and everything that follows is the same in every tier.
                What differs is what you run and where it ends up, which is what this page is
                about.
              </p>

              <h2>Before you start</h2>
              <ul>
                  <li>
                    <strong>Go 1.21 or newer</strong> &mdash; The API, and the binary that ends up carrying everything.
                  </li>
                  <li>
                    <strong>Node 20 or newer, with pnpm</strong> &mdash; To build the frontend. Only at build time: the server needs nothing.
                  </li>
              </ul>
              <p>
                And Grit itself: <code>go install github.com/MUKE-coder/grit/v3/cmd/grit@latest</code>.
              </p>

              <h2>1. Create the project</h2>
              <CodeBlock terminal language="bash" code={`grit new contacts --single --theme emerald --db sqlite
cd contacts`} />
              <p>
                Postgres is the default. <code>--db sqlite</code> above means the project runs
                with no database server at all, which is the shortest path to seeing it work; drop
                the flag when you want Postgres, and <code>docker compose up -d</code> brings one
                up along with Redis, MinIO and a mail catcher.
              </p>

              <h3>Next.js or TanStack</h3>
              <p>
                The command above builds the frontend with Next.js. The same tier with TanStack
                Router and Vite instead is one flag:
              </p>
              <CodeBlock terminal language="bash" code={`grit new contacts --single --next --theme emerald --db sqlite`} />
              <p>
                Everything after this point is identical. The resources, the API, the admin
                screens and the deployment are the same; what changes is the router and the build
                tool, and the admin panel is written in whichever dialect that app speaks.
              </p>

              <h3>Pick a theme</h3>
              <p>
                <code>--theme</code> sets the sign-in layout, the dashboard tokens, the fonts and
                the brand colours, and it applies to both frontends. Eight ship with Grit:
              </p>

              <table className="w-full text-sm my-6">
                <thead>
                  <tr className="border-b border-border/50 text-left">
                    <th className="px-4 py-2.5 font-medium">Theme</th>
                    <th className="px-4 py-2.5 font-medium">What it looks like</th>
                  </tr>
                </thead>
                <tbody>
                  <tr className="border-b border-border/30">
                    <td className="px-4 py-2.5 font-mono text-xs text-primary">atlas</td>
                    <td className="px-4 py-2.5 text-muted-foreground">Split-screen sign-in, Inter. The default: sharp and neutral, for a team tool.</td>
                  </tr>
                  <tr className="border-b border-border/30">
                    <td className="px-4 py-2.5 font-mono text-xs text-primary">aurora</td>
                    <td className="px-4 py-2.5 text-muted-foreground">Centered sign-in, Geist. Pastel and friendly, for consumer software.</td>
                  </tr>
                  <tr className="border-b border-border/30">
                    <td className="px-4 py-2.5 font-mono text-xs text-primary">pulse</td>
                    <td className="px-4 py-2.5 text-muted-foreground">Split-screen with a carousel, Onest and DM Serif. Warm and bold, for a brand.</td>
                  </tr>
                  <tr className="border-b border-border/30">
                    <td className="px-4 py-2.5 font-mono text-xs text-primary">coral</td>
                    <td className="px-4 py-2.5 text-muted-foreground">A sign-in modal over the page. Soft, close up.</td>
                  </tr>
                  <tr className="border-b border-border/30">
                    <td className="px-4 py-2.5 font-mono text-xs text-primary">amber</td>
                    <td className="px-4 py-2.5 text-muted-foreground">A boxed sign-in card. Warm neutrals.</td>
                  </tr>
                  <tr className="border-b border-border/30">
                    <td className="px-4 py-2.5 font-mono text-xs text-primary">sky</td>
                    <td className="px-4 py-2.5 text-muted-foreground">A banner above the form. Open and light.</td>
                  </tr>
                  <tr className="border-b border-border/30">
                    <td className="px-4 py-2.5 font-mono text-xs text-primary">mono</td>
                    <td className="px-4 py-2.5 text-muted-foreground">A showcase panel beside the form. Monochrome and typographic.</td>
                  </tr>
                  <tr className="border-b border-border/30">
                    <td className="px-4 py-2.5 font-mono text-xs text-primary">emerald</td>
                    <td className="px-4 py-2.5 text-muted-foreground">A quote beside the form. Green and calm: the one the commands above use.</td>
                  </tr>
                </tbody>
              </table>

              <p>
                Nothing is baked in. <code>THEME</code> and <code>VITE_THEME</code> in{' '}
                <code>.env</code> both carry the name, so changing it there repaints the app
                without re-scaffolding.
              </p>


              <table className="w-full text-sm my-6">
                <thead>
                  <tr className="border-b border-border/50 text-left">
                    <th className="px-4 py-2.5 font-medium">Directory</th>
                    <th className="px-4 py-2.5 font-medium">What is in it</th>
                  </tr>
                </thead>
                <tbody>
                  <tr className="border-b border-border/30">
                    <td className="px-4 py-2.5 font-mono text-xs text-primary">src</td>
                    <td className="px-4 py-2.5 text-muted-foreground">The Vite app: routes, components, and the admin panel under admin-panel/</td>
                  </tr>
                  <tr className="border-b border-border/30">
                    <td className="px-4 py-2.5 font-mono text-xs text-primary">api</td>
                    <td className="px-4 py-2.5 text-muted-foreground">The Go module: main.go, internal/, cmd/</td>
                  </tr>
                  <tr className="border-b border-border/30">
                    <td className="px-4 py-2.5 font-mono text-xs text-primary">api/web</td>
                    <td className="px-4 py-2.5 text-muted-foreground">Where the frontend build lands, so the binary can embed it</td>
                  </tr>
                  <tr className="border-b border-border/30">
                    <td className="px-4 py-2.5 font-mono text-xs text-primary">packages</td>
                    <td className="px-4 py-2.5 text-muted-foreground">The upload client the frontend shares with the API</td>
                  </tr>
                </tbody>
              </table>

              <h2>2. Describe the data</h2>
              <p>
                A group first, because a contact points at one. Each command writes the Go model,
                the migration, the service, the handler, the routes, the Zod schema, the
                TypeScript types and an admin screen, and registers all of it.
              </p>
              <CodeBlock terminal language="bash" code={`grit generate resource Group \\
  --fields "name:string,description:text"`} />
              <p>
                Then the contact, with a photo and a group to belong to. The{' '}
                <code>belongs_to:Group</code> field is what makes the admin screen render a picker
                rather than a text box asking for an id.
              </p>
              <CodeBlock terminal language="bash" code={`grit generate resource Contact \\
  --fields "name:string,email:email,phone:tel,photo:file:image,group:belongs_to:Group"`} />

              <h2>3. Build the database</h2>
              <CodeBlock terminal language="bash" code={`grit migrate
grit seed`} />
              <p>
                <code>grit migrate</code> creates the tables from the models, and{' '}
                <code>grit seed</code> fills them: an administrator you can sign in as, a few
                users, and an API key. The administrator is{' '}
                <code>admin@example.com</code> with the password <code>admin123</code>. Change it
                before anybody else can reach the machine.
              </p>

              <h2>4. Run it</h2>
              <CodeBlock terminal language="bash" code={`grit start`} />
              <p>The Go API and the Vite dev server, in parallel. In development they are two processes; in production they are one file.</p>

              <table className="w-full text-sm my-6">
                <thead>
                  <tr className="border-b border-border/50 text-left">
                    <th className="px-4 py-2.5 font-medium">Where</th>
                    <th className="px-4 py-2.5 font-medium">What</th>
                  </tr>
                </thead>
                <tbody>
                  <tr className="border-b border-border/30">
                    <td className="px-4 py-2.5 font-mono text-xs text-primary">http://localhost:5173</td>
                    <td className="px-4 py-2.5 text-muted-foreground">The app, with the admin panel at /admin</td>
                  </tr>
                  <tr className="border-b border-border/30">
                    <td className="px-4 py-2.5 font-mono text-xs text-primary">http://localhost:8080/api/v1</td>
                    <td className="px-4 py-2.5 text-muted-foreground">The API</td>
                  </tr>
                  <tr className="border-b border-border/30">
                    <td className="px-4 py-2.5 font-mono text-xs text-primary">http://localhost:8080/docs</td>
                    <td className="px-4 py-2.5 text-muted-foreground">The reference</td>
                  </tr>
                </tbody>
              </table>

              <h2>5. What you have</h2>
              <p>
                Two resources, and for each of them: a table with sorting, filtering, search,
                pagination, bulk edit and CSV import and export; a form that validates on both
                sides from one schema; and REST endpoints under <code>/api/v1/groups</code> and{' '}
                <code>/api/v1/contacts</code> with the same rules applied.
              </p>
              <p>
                The photo field is a real upload: the browser asks the API for a presigned URL and
                sends the file straight to storage, so the file never passes through the API
                process. With <code>STORAGE_DRIVER=local</code> that storage is a directory on
                disk, which is the default when there is no MinIO to talk to.
              </p>

              <h2>6. Deploy it</h2>
              <CodeBlock terminal language="bash" code={`# Build the frontend into api/web, then the binary around it
pnpm build
cd api && go build -o ../bin/contacts .

# That one file is the deployment
scp bin/contacts user@server.com:/srv/contacts

# Or let grit do the systemd and TLS part
grit deploy --host user@server.com --domain contacts.example.com`} />
              <p>The binary serves the API and the whole frontend, so there is nothing else to put on the server: no Node, no nginx in front of static files, no second process. Copy it beside a <code>.env</code> and run it. <code>grit deploy</code> does the same thing and adds a systemd unit and a certificate.</p>
              <p>
                Before any of that, read the{' '}
                <Link href="/docs/deployment/checklist">go-live checklist</Link>: it is the list of
                things that are fine in development and not in production, starting with the
                seeded password above and the secrets in <code>.env</code>.
              </p>
            </div>

            <div className="mt-16 flex flex-col sm:flex-row gap-4 justify-between border-t border-border pt-8">
              <Button variant="ghost" asChild>
                <Link href="/docs/tutorials/contacts/api">
                  <ArrowLeft className="mr-2 h-4 w-4" />
                  The API on its own
                </Link>
              </Button>
              <Button variant="ghost" asChild>
                <Link href="/docs/tutorials/contacts/full">
                  Everything at once
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Link>
              </Button>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
