package expose

import (
	"fmt"
	"strings"

	"github.com/MUKE-coder/grit/v3/internal/generate"
)

// fieldRow describes a single form/table field after filtering and
// type-mapping. Used by both buildFormPage and buildTablePage so the
// two templates produce a consistent column / input set.
type fieldRow struct {
	JSONName string // snake_case key as it appears in the API payload
	Label    string // human label ("Phone number")
	GoType   string // "string", "int", "bool", "*time.Time", …
	IsTime   bool   // simplifies template branching
}

// autoFields returns the user-relevant fields from a struct, dropping
// framework-owned columns (id / version / *_at) and relationship
// associations (both pointer + value form). Order matches the struct
// declaration.
func autoFields(s *generate.GoStruct) []fieldRow {
	out := make([]fieldRow, 0, len(s.Fields))
	for _, f := range s.Fields {
		switch f.Name {
		case "ID", "Version", "CreatedAt", "UpdatedAt", "DeletedAt":
			continue
		}
		// Only render fields whose Go type is a primitive we know how
		// to bind to an <input>. Skips relationship associations
		// (`Group *Group`, `Group Group`, `Tags []Tag`), embedded
		// JSON columns, custom enum types, etc. The FK columns
		// (`GroupID string`) still come through.
		if !isPrimitiveGoType(f.GoType) {
			continue
		}
		jsonName := f.JSONName
		if jsonName == "" {
			jsonName = camelToSnake(f.Name)
		}
		out = append(out, fieldRow{
			JSONName: jsonName,
			Label:    labelFromJSONName(jsonName),
			GoType:   f.GoType,
			IsTime:   strings.Contains(f.GoType, "time.Time"),
		})
	}
	return out
}

// isPrimitiveGoType returns true for the small set of Go types we can
// safely map to a single <input> or <textarea>. Anything else (structs,
// slices of structs, JSON columns) is dropped from the generated page —
// operators can hand-add custom controls afterward if they need them.
func isPrimitiveGoType(t string) bool {
	switch t {
	case "string", "bool",
		"int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64",
		"time.Time", "*time.Time":
		return true
	}
	return false
}

// labelFromJSONName turns "group_id" into "Group id" — cheap title-case
// from the snake-case JSON tag. Handles acronyms naturally (the snake
// form already preserves them).
func labelFromJSONName(name string) string {
	parts := strings.Split(name, "_")
	if len(parts) == 0 || parts[0] == "" {
		return name
	}
	parts[0] = strings.ToUpper(parts[0][:1]) + parts[0][1:]
	return strings.Join(parts, " ")
}

// buildFormPage emits a Next.js client page that renders one input per
// field + submits via the generated useCreate<Resource>() hook. The
// page intentionally uses plain Tailwind (no @repo/admin imports) so
// it can sit on a public marketing site without dragging admin chrome.
func buildFormPage(resource string, s *generate.GoStruct) string {
	plural := pluralKebab(resource)
	rows := autoFields(s)

	var inputs strings.Builder
	for _, r := range rows {
		inputs.WriteString(formInput(r))
	}

	return fmt.Sprintf(`"use client";

// AUTO-GENERATED by ` + "`grit expose form %s`" + `. Safe to edit — this file
// is not re-emitted by sync. Re-run grit expose form to overwrite.
//
// Note: server-side validation is the source of truth. The shared Zod
// schema (Create%sSchema) uses camelCase field names by convention,
// but the Go API expects snake_case JSON keys — so we use plain
// react-hook-form without a Zod resolver here, and submit snake_case
// keys directly. Add client-side validation by hand if you need it,
// or wait for the resolver to grow snake-case-alias support.

import { useState } from "react";
import { useForm } from "react-hook-form";
import { useCreate%s } from "@/hooks/use-%s";

export default function %sFormPage() {
  const [done, setDone] = useState(false);
  const { mutate: create, isPending, error: serverError } = useCreate%s();
  const {
    register,
    handleSubmit,
    reset,
    formState: { errors },
  } = useForm<Record<string, unknown>>();

  const onSubmit = (input: Record<string, unknown>) => {
    create(input, {
      onSuccess: () => {
        setDone(true);
        reset();
      },
    });
  };

  if (done) {
    return (
      <main className="flex min-h-screen items-center justify-center bg-slate-50 p-4">
        <div className="w-full max-w-md rounded-2xl border border-emerald-200 bg-emerald-50 p-8 text-center shadow-sm">
          <h1 className="text-xl font-semibold text-emerald-900">Thank you</h1>
          <p className="mt-2 text-sm text-emerald-700">Your %s submission was received.</p>
          <button
            type="button"
            onClick={() => setDone(false)}
            className="mt-4 text-xs font-medium text-emerald-800 underline"
          >
            Submit another
          </button>
        </div>
      </main>
    );
  }

  const serverMessage = (serverError as unknown as { response?: { data?: { error?: { message?: string } } } })
    ?.response?.data?.error?.message;

  return (
    <main className="flex min-h-screen items-center justify-center bg-slate-50 p-4">
      <div className="w-full max-w-md rounded-2xl border border-slate-200 bg-white p-8 shadow-sm">
        <h1 className="text-2xl font-semibold text-slate-900">New %s</h1>
        <p className="mt-1 text-sm text-slate-500">Fill out the form below to submit.</p>

        <form onSubmit={handleSubmit(onSubmit)} className="mt-6 space-y-4">
%s
          {serverMessage && (
            <p className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">
              {serverMessage}
            </p>
          )}

          <button
            type="submit"
            disabled={isPending}
            className="w-full rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white hover:bg-slate-800 disabled:opacity-50"
          >
            {isPending ? "Sending…" : "Submit"}
          </button>
        </form>
      </div>
    </main>
  );
}
`,
		resource,                  // grit expose form %s (header comment)
		resource,                  // schema (Create%sSchema) — comment
		resource, plural,          // useCreate%s from "@/hooks/use-%s"
		resource,                  // function %sFormPage
		resource,                  // useCreate%s()
		strings.ToLower(resource), // "Your %s submission was received"
		resource,                  // "New %s"
		inputs.String(),           // form inputs
	)
}

// formInput emits one labelled input element. The input type is
// derived from the Go field's type (string → text, *time.Time → date,
// bool → checkbox, etc).
func formInput(r fieldRow) string {
	inputType := "text"
	switch r.GoType {
	case "int", "uint", "int32", "int64", "uint32", "uint64", "float64", "float32":
		inputType = "number"
	case "bool":
		// rendered as a checkbox below
	}
	if r.IsTime {
		inputType = "date"
	}

	if r.GoType == "bool" {
		return fmt.Sprintf(`          <label className="flex items-center gap-2 text-sm text-slate-700">
            <input type="checkbox" {...register("%s")} className="rounded border-slate-300" />
            %s
          </label>
`, r.JSONName, r.Label)
	}

	if isLikelyLongText(r.JSONName) {
		return fmt.Sprintf(`          <div className="space-y-1.5">
            <label className="block text-sm font-medium text-slate-700">%s</label>
            <textarea
              rows={4}
              {...register("%s")}
              className="block w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 placeholder-slate-400 focus:border-slate-900 focus:outline-none focus:ring-2 focus:ring-slate-900/10"
            />
            {errors.%s && <p className="text-sm text-red-600">{errors.%s.message as string}</p>}
          </div>
`, r.Label, r.JSONName, r.JSONName, r.JSONName)
	}

	return fmt.Sprintf(`          <div className="space-y-1.5">
            <label className="block text-sm font-medium text-slate-700">%s</label>
            <input
              type="%s"
              {...register("%s")}
              className="block w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 placeholder-slate-400 focus:border-slate-900 focus:outline-none focus:ring-2 focus:ring-slate-900/10"
            />
            {errors.%s && <p className="text-sm text-red-600">{errors.%s.message as string}</p>}
          </div>
`, r.Label, inputType, r.JSONName, r.JSONName, r.JSONName)
}

// buildTablePage emits a Next.js client page that renders a paginated,
// searchable list using the use<Resources>() hook. The columns mirror
// the model's user-relevant fields (no id, no timestamps, no
// relationship pointers).
func buildTablePage(resource string, s *generate.GoStruct) string {
	plural := pluralKebab(resource)
	pluralP := pluralPascal(resource)
	rows := autoFields(s)

	var headers strings.Builder
	var cells strings.Builder
	for _, r := range rows {
		headers.WriteString(fmt.Sprintf(`              <th className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider text-slate-500">%s</th>
`, r.Label))
		cells.WriteString(fmt.Sprintf(`                <td className="px-4 py-3 text-sm text-slate-700">{String(row.%s ?? "")}</td>
`, r.JSONName))
	}

	return fmt.Sprintf(`"use client";

// AUTO-GENERATED by ` + "`grit expose table %s`" + `. Safe to edit — this file
// is not re-emitted by sync. Re-run grit expose table to overwrite.

import { useState } from "react";
import { use%s } from "@/hooks/use-%s";

export default function %sTablePage() {
  const [search, setSearch] = useState("");
  const [page, setPage] = useState(1);

  const { data, isLoading } = use%s({ search, page, pageSize: 20 });

  const rows = (data?.data ?? []) as unknown as Record<string, unknown>[];
  const pages = data?.meta?.pages ?? 1;

  return (
    <main className="mx-auto min-h-screen max-w-5xl bg-slate-50 p-4 sm:p-8">
      <header className="mb-6 flex items-center justify-between gap-4">
        <h1 className="text-2xl font-semibold text-slate-900">%s</h1>
        <input
          value={search}
          onChange={(e) => { setSearch(e.target.value); setPage(1); }}
          placeholder="Search…"
          className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 placeholder-slate-400 focus:border-slate-900 focus:outline-none focus:ring-2 focus:ring-slate-900/10"
        />
      </header>

      <div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
        <table className="w-full">
          <thead className="border-b border-slate-200 bg-slate-50">
            <tr>
%s            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100">
            {isLoading ? (
              <tr><td colSpan={99} className="px-4 py-12 text-center text-sm text-slate-500">Loading…</td></tr>
            ) : rows.length === 0 ? (
              <tr><td colSpan={99} className="px-4 py-12 text-center text-sm text-slate-500">No %s yet.</td></tr>
            ) : rows.map((row, i) => (
              <tr key={(row.id as string) ?? i} className="hover:bg-slate-50">
%s              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <footer className="mt-4 flex items-center justify-between text-sm text-slate-600">
        <span>Page {page} of {pages}</span>
        <div className="flex gap-2">
          <button
            type="button"
            onClick={() => setPage((p) => Math.max(1, p - 1))}
            disabled={page === 1}
            className="rounded-lg border border-slate-300 bg-white px-3 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-50 disabled:opacity-50"
          >
            Previous
          </button>
          <button
            type="button"
            onClick={() => setPage((p) => Math.min(pages, p + 1))}
            disabled={page >= pages}
            className="rounded-lg border border-slate-300 bg-white px-3 py-1.5 text-xs font-medium text-slate-700 hover:bg-slate-50 disabled:opacity-50"
          >
            Next
          </button>
        </div>
      </footer>
    </main>
  );
}
`,
		resource,           // expose table %s
		pluralP,            // useXxx
		plural,             // use-<plural>
		resource,           // function name
		pluralP,            // useXxx({…})
		plural,             // "<Plural>"  — header
		headers.String(),
		plural,             // "No <plural> yet"
		cells.String(),
	)
}

// camelToSnake is a stripped-down version of the helper from generate
// (kept local so this package has no internal dependencies beyond
// generate.ParseGoStructs / generate.GoStruct).
func camelToSnake(s string) string {
	var b strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			b.WriteByte('_')
		}
		if r >= 'A' && r <= 'Z' {
			b.WriteRune(r - 'A' + 'a')
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// isLikelyLongText mirrors the heuristic the admin generator uses to
// pick textarea over text. Kept in sync (loosely — adding a name here
// makes the expose pages render a wider input).
func isLikelyLongText(name string) bool {
	switch name {
	case "description", "notes", "content", "body", "summary", "bio", "details",
		"comment", "comments", "message":
		return true
	}
	return false
}
