import { CodeBlock } from '@/components/code-block'
import { TipBox } from '@/components/course/tip-box'
import { Exercise } from '@/components/course/exercise'
import { KnowledgeCheck } from '@/components/course/knowledge-check'

export default function Lesson() {
  return (
    <>
      <p>
        Grit has one place for everything. That sounds like a constraint —
        it&apos;s actually a superpower. Every team member, every AI agent, every
        future-you knows where to look without thinking. This lesson covers
        the rules.
      </p>

      <h2>The four big places</h2>
      <ul>
        <li><strong>apps/api/cmd/</strong> — entry points (just <code>server/main.go</code> usually)</li>
        <li><strong>apps/api/internal/</strong> — everything that&apos;s not exported. The actual code lives here.</li>
        <li><strong>apps/web/</strong> + <strong>apps/admin/</strong> — Next.js apps. Standard App Router shape.</li>
        <li><strong>packages/shared/</strong> — Zod + TS types. Imported by web and admin.</li>
      </ul>

      <h2>internal/ — the seven sub-folders that matter</h2>
      <CodeBlock
        language="text"
        filename="apps/api/internal/"
        code={`internal/
├── config/       Loads .env into a typed Config struct.
├── database/     Postgres connection + AutoMigrate.
├── handlers/     HTTP handlers — thin, one per resource.
├── middleware/   auth, CORS, security, request ID, etc.
├── models/       GORM struct definitions.
├── routes/       routes.go — mounts every handler on a route.
└── services/     Business logic — called by handlers.`}
      />

      <h3>The flow of a request</h3>
      <CodeBlock
        language="text"
        code={`HTTP request
  → middleware (auth, CORS, security)
  → routes/routes.go picks the handler
  → handlers/x.go parses input, calls services
  → services/x.go does the work, calls models
  → models/x.go is the GORM struct used to read/write DB
  → response shaped by handler, sent back`}
      />

      <TipBox tone="success">
        <strong>The rule:</strong> handlers are thin, services are thick.
        Handlers should be ~20 lines (parse → call service → return).
        Anything else — DB queries, validation, side effects — belongs in a
        service.
      </TipBox>

      <h2>packages/shared/ — the type bridge</h2>
      <CodeBlock
        language="text"
        filename="packages/shared/"
        code={`packages/shared/
├── src/
│   ├── schemas/     Zod schemas (used to validate API calls)
│   ├── types/       TS types (generated by grit sync from Go structs)
│   └── constants/   Route constants, enums, shared values.
└── package.json     Imported as @workspace/shared by web + admin`}
      />

      <h2>What does NOT go in internal/</h2>
      <ul>
        <li>
          <strong>Tests</strong> — they live alongside the file they test:{' '}
          <code>handlers/user.go</code> → <code>handlers/user_test.go</code>.
        </li>
        <li>
          <strong>Migrations</strong> — Grit uses GORM AutoMigrate by
          default. No <code>internal/migrations/</code> folder.
        </li>
        <li>
          <strong>Static assets</strong> — frontend assets live in{' '}
          <code>apps/web/public/</code> or <code>apps/admin/public/</code>.
        </li>
      </ul>

      <KnowledgeCheck
        question="You need to add a function that validates a phone number — used by signup AND by the admin panel's user form. Where does it go?"
        choices={[
          {
            label: 'apps/api/internal/services/phone.go',
            feedback:
              "Half right — yes, if only the API uses it. But the admin form needs it too, and admin runs in the browser. A Go-only service can't validate on the frontend.",
          },
          {
            label: 'apps/web/lib/phone.ts AND apps/admin/lib/phone.ts (copy)',
            feedback:
              "Wrong — duplicating shared logic is exactly what packages/shared exists to prevent. They'll drift.",
          },
          {
            label: 'packages/shared/src/schemas/phone.ts (Zod schema)',
            correct: true,
            feedback:
              "Right — packages/shared is the type bridge. A Zod schema for phone validation lives there; web, admin, AND the API (via grit sync's generated counterpart) all use it.",
          },
          {
            label: 'apps/api/internal/handlers/phone.go',
            feedback:
              "Wrong — validation is not handler logic. Handlers shouldn't own business rules.",
          },
        ]}
      />

      <Exercise
        prompt={
          <>
            <p>
              You need to add a <strong>NotificationService</strong> that
              sends push notifications when a user&apos;s order ships. Decide
              where each piece goes — write it in <code>notes.md</code>:
            </p>
            <ol>
              <li>The struct + methods that talk to Expo Push?</li>
              <li>The DB row that tracks &quot;was this notification sent?&quot;</li>
              <li>The HTTP endpoint to trigger a test push from the admin panel?</li>
              <li>The TypeScript type for the admin form&apos;s payload?</li>
            </ol>
          </>
        }
        hint={
          <>
            Trace each piece against the &quot;handler/service/model/shared&quot; map.
          </>
        }
        solution={
          <>
            <ol>
              <li><code>apps/api/internal/services/notification.go</code></li>
              <li><code>apps/api/internal/models/notification.go</code></li>
              <li><code>apps/api/internal/handlers/notification.go</code> (calls the service)</li>
              <li><code>packages/shared/src/schemas/notification.ts</code> (Zod schema)</li>
            </ol>
            <p>
              Four files, four homes, no decisions needed. That&apos;s the
              point.
            </p>
          </>
        }
      />

      <h2>What&apos;s next</h2>
      <p>
        Folders sorted. Next — naming. snake_case for Go files, kebab-case
        for TS, plural for routes. Same logic: one rule, applied everywhere.
      </p>
    </>
  )
}
