/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppSparesRouteImport } from './routes/_app/spares'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPosRouteImport } from './routes/_app/pos'
import { Route as AppLoansOverviewRouteImport } from './routes/_app/loans-overview'
import { Route as AppActivitiesRouteImport } from './routes/_app/activities'
import { Route as AppStockIndexRouteImport } from './routes/_app/stock/index'
import { Route as AppStaffIndexRouteImport } from './routes/_app/staff/index'
import { Route as AppSalesIndexRouteImport } from './routes/_app/sales/index'
import { Route as AppReportsIndexRouteImport } from './routes/_app/reports/index'
import { Route as AppRepaymentsIndexRouteImport } from './routes/_app/repayments/index'
import { Route as AppProductsIndexRouteImport } from './routes/_app/products/index'
import { Route as AppMotorcyclesIndexRouteImport } from './routes/_app/motorcycles/index'
import { Route as AppLoansIndexRouteImport } from './routes/_app/loans/index'
import { Route as AppLoanProductsIndexRouteImport } from './routes/_app/loan-products/index'
import { Route as AppCashSalesIndexRouteImport } from './routes/_app/cash-sales/index'
import { Route as AppBranchesIndexRouteImport } from './routes/_app/branches/index'
import { Route as AppBorrowersIndexRouteImport } from './routes/_app/borrowers/index'
import { Route as AppSystemSecurityRouteImport } from './routes/_app/system/security'
import { Route as AppSystemObservabilityRouteImport } from './routes/_app/system/observability'
import { Route as AppStockTransferRouteImport } from './routes/_app/stock/transfer'
import { Route as AppStockMovementsRouteImport } from './routes/_app/stock/movements'
import { Route as AppStockInRouteImport } from './routes/_app/stock/in'
import { Route as AppStaffInviteRouteImport } from './routes/_app/staff/invite'
import { Route as AppSalesIdRouteImport } from './routes/_app/sales/$id'
import { Route as AppReportsStockRouteImport } from './routes/_app/reports/stock'
import { Route as AppReportsPnlRouteImport } from './routes/_app/reports/pnl'
import { Route as AppReportsPerformanceRouteImport } from './routes/_app/reports/performance'
import { Route as AppReportsMotorcyclesRouteImport } from './routes/_app/reports/motorcycles'
import { Route as AppReportsLoansRouteImport } from './routes/_app/reports/loans'
import { Route as AppReportsDailyBodaRouteImport } from './routes/_app/reports/daily-boda'
import { Route as AppReportsDailyRouteImport } from './routes/_app/reports/daily'
import { Route as AppReportsCollectionsRouteImport } from './routes/_app/reports/collections'
import { Route as AppReportsCashiersRouteImport } from './routes/_app/reports/cashiers'
import { Route as AppProductsNewRouteImport } from './routes/_app/products/new'
import { Route as AppProductsIdRouteImport } from './routes/_app/products/$id'
import { Route as AppMotorcyclesIdRouteImport } from './routes/_app/motorcycles/$id'
import { Route as AppLoansNewRouteImport } from './routes/_app/loans/new'
import { Route as AppLoansIdRouteImport } from './routes/_app/loans/$id'
import { Route as AppDailyBodaPaymentsRouteImport } from './routes/_app/daily-boda/payments'
import { Route as AppDailyBodaMotorcyclesRouteImport } from './routes/_app/daily-boda/motorcycles'
import { Route as AppDailyBodaDriversRouteImport } from './routes/_app/daily-boda/drivers'
import { Route as AppCashSalesNewRouteImport } from './routes/_app/cash-sales/new'
import { Route as AppCashSalesIdRouteImport } from './routes/_app/cash-sales/$id'
import { Route as AppBranchesNewRouteImport } from './routes/_app/branches/new'
import { Route as AppBorrowersIdRouteImport } from './routes/_app/borrowers/$id'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppSparesRoute = AppSparesRouteImport.update({
  id: '/spares',
  path: '/spares',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansOverviewRoute = AppLoansOverviewRouteImport.update({
  id: '/loans-overview',
  path: '/loans-overview',
  getParentRoute: () => AppRoute,
} as any)
const AppActivitiesRoute = AppActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AppRoute,
} as any)
const AppStockIndexRoute = AppStockIndexRouteImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffIndexRoute = AppStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesIndexRoute = AppSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppRepaymentsIndexRoute = AppRepaymentsIndexRouteImport.update({
  id: '/repayments/',
  path: '/repayments/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppMotorcyclesIndexRoute = AppMotorcyclesIndexRouteImport.update({
  id: '/motorcycles/',
  path: '/motorcycles/',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansIndexRoute = AppLoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => AppRoute,
} as any)
const AppLoanProductsIndexRoute = AppLoanProductsIndexRouteImport.update({
  id: '/loan-products/',
  path: '/loan-products/',
  getParentRoute: () => AppRoute,
} as any)
const AppCashSalesIndexRoute = AppCashSalesIndexRouteImport.update({
  id: '/cash-sales/',
  path: '/cash-sales/',
  getParentRoute: () => AppRoute,
} as any)
const AppBranchesIndexRoute = AppBranchesIndexRouteImport.update({
  id: '/branches/',
  path: '/branches/',
  getParentRoute: () => AppRoute,
} as any)
const AppBorrowersIndexRoute = AppBorrowersIndexRouteImport.update({
  id: '/borrowers/',
  path: '/borrowers/',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemSecurityRoute = AppSystemSecurityRouteImport.update({
  id: '/system/security',
  path: '/system/security',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemObservabilityRoute = AppSystemObservabilityRouteImport.update({
  id: '/system/observability',
  path: '/system/observability',
  getParentRoute: () => AppRoute,
} as any)
const AppStockTransferRoute = AppStockTransferRouteImport.update({
  id: '/stock/transfer',
  path: '/stock/transfer',
  getParentRoute: () => AppRoute,
} as any)
const AppStockMovementsRoute = AppStockMovementsRouteImport.update({
  id: '/stock/movements',
  path: '/stock/movements',
  getParentRoute: () => AppRoute,
} as any)
const AppStockInRoute = AppStockInRouteImport.update({
  id: '/stock/in',
  path: '/stock/in',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffInviteRoute = AppStaffInviteRouteImport.update({
  id: '/staff/invite',
  path: '/staff/invite',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesIdRoute = AppSalesIdRouteImport.update({
  id: '/sales/$id',
  path: '/sales/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsStockRoute = AppReportsStockRouteImport.update({
  id: '/reports/stock',
  path: '/reports/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsPnlRoute = AppReportsPnlRouteImport.update({
  id: '/reports/pnl',
  path: '/reports/pnl',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsPerformanceRoute = AppReportsPerformanceRouteImport.update({
  id: '/reports/performance',
  path: '/reports/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsMotorcyclesRoute = AppReportsMotorcyclesRouteImport.update({
  id: '/reports/motorcycles',
  path: '/reports/motorcycles',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsLoansRoute = AppReportsLoansRouteImport.update({
  id: '/reports/loans',
  path: '/reports/loans',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsDailyBodaRoute = AppReportsDailyBodaRouteImport.update({
  id: '/reports/daily-boda',
  path: '/reports/daily-boda',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsDailyRoute = AppReportsDailyRouteImport.update({
  id: '/reports/daily',
  path: '/reports/daily',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsCollectionsRoute = AppReportsCollectionsRouteImport.update({
  id: '/reports/collections',
  path: '/reports/collections',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsCashiersRoute = AppReportsCashiersRouteImport.update({
  id: '/reports/cashiers',
  path: '/reports/cashiers',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsNewRoute = AppProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIdRoute = AppProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMotorcyclesIdRoute = AppMotorcyclesIdRouteImport.update({
  id: '/motorcycles/$id',
  path: '/motorcycles/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansNewRoute = AppLoansNewRouteImport.update({
  id: '/loans/new',
  path: '/loans/new',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansIdRoute = AppLoansIdRouteImport.update({
  id: '/loans/$id',
  path: '/loans/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDailyBodaPaymentsRoute = AppDailyBodaPaymentsRouteImport.update({
  id: '/daily-boda/payments',
  path: '/daily-boda/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppDailyBodaMotorcyclesRoute = AppDailyBodaMotorcyclesRouteImport.update({
  id: '/daily-boda/motorcycles',
  path: '/daily-boda/motorcycles',
  getParentRoute: () => AppRoute,
} as any)
const AppDailyBodaDriversRoute = AppDailyBodaDriversRouteImport.update({
  id: '/daily-boda/drivers',
  path: '/daily-boda/drivers',
  getParentRoute: () => AppRoute,
} as any)
const AppCashSalesNewRoute = AppCashSalesNewRouteImport.update({
  id: '/cash-sales/new',
  path: '/cash-sales/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCashSalesIdRoute = AppCashSalesIdRouteImport.update({
  id: '/cash-sales/$id',
  path: '/cash-sales/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBranchesNewRoute = AppBranchesNewRouteImport.update({
  id: '/branches/new',
  path: '/branches/new',
  getParentRoute: () => AppRoute,
} as any)
const AppBorrowersIdRoute = AppBorrowersIdRouteImport.update({
  id: '/borrowers/$id',
  path: '/borrowers/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/activities': typeof AppActivitiesRoute
  '/loans-overview': typeof AppLoansOverviewRoute
  '/pos': typeof AppPosRoute
  '/settings': typeof AppSettingsRoute
  '/spares': typeof AppSparesRoute
  '/login': typeof AuthLoginRoute
  '/invite/$token': typeof InviteTokenRoute
  '/borrowers/$id': typeof AppBorrowersIdRoute
  '/branches/new': typeof AppBranchesNewRoute
  '/cash-sales/$id': typeof AppCashSalesIdRoute
  '/cash-sales/new': typeof AppCashSalesNewRoute
  '/daily-boda/drivers': typeof AppDailyBodaDriversRoute
  '/daily-boda/motorcycles': typeof AppDailyBodaMotorcyclesRoute
  '/daily-boda/payments': typeof AppDailyBodaPaymentsRoute
  '/loans/$id': typeof AppLoansIdRoute
  '/loans/new': typeof AppLoansNewRoute
  '/motorcycles/$id': typeof AppMotorcyclesIdRoute
  '/products/$id': typeof AppProductsIdRoute
  '/products/new': typeof AppProductsNewRoute
  '/reports/cashiers': typeof AppReportsCashiersRoute
  '/reports/collections': typeof AppReportsCollectionsRoute
  '/reports/daily': typeof AppReportsDailyRoute
  '/reports/daily-boda': typeof AppReportsDailyBodaRoute
  '/reports/loans': typeof AppReportsLoansRoute
  '/reports/motorcycles': typeof AppReportsMotorcyclesRoute
  '/reports/performance': typeof AppReportsPerformanceRoute
  '/reports/pnl': typeof AppReportsPnlRoute
  '/reports/stock': typeof AppReportsStockRoute
  '/sales/$id': typeof AppSalesIdRoute
  '/staff/invite': typeof AppStaffInviteRoute
  '/stock/in': typeof AppStockInRoute
  '/stock/movements': typeof AppStockMovementsRoute
  '/stock/transfer': typeof AppStockTransferRoute
  '/system/observability': typeof AppSystemObservabilityRoute
  '/system/security': typeof AppSystemSecurityRoute
  '/borrowers/': typeof AppBorrowersIndexRoute
  '/branches/': typeof AppBranchesIndexRoute
  '/cash-sales/': typeof AppCashSalesIndexRoute
  '/loan-products/': typeof AppLoanProductsIndexRoute
  '/loans/': typeof AppLoansIndexRoute
  '/motorcycles/': typeof AppMotorcyclesIndexRoute
  '/products/': typeof AppProductsIndexRoute
  '/repayments/': typeof AppRepaymentsIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/sales/': typeof AppSalesIndexRoute
  '/staff/': typeof AppStaffIndexRoute
  '/stock/': typeof AppStockIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/activities': typeof AppActivitiesRoute
  '/loans-overview': typeof AppLoansOverviewRoute
  '/pos': typeof AppPosRoute
  '/settings': typeof AppSettingsRoute
  '/spares': typeof AppSparesRoute
  '/login': typeof AuthLoginRoute
  '/invite/$token': typeof InviteTokenRoute
  '/borrowers/$id': typeof AppBorrowersIdRoute
  '/branches/new': typeof AppBranchesNewRoute
  '/cash-sales/$id': typeof AppCashSalesIdRoute
  '/cash-sales/new': typeof AppCashSalesNewRoute
  '/daily-boda/drivers': typeof AppDailyBodaDriversRoute
  '/daily-boda/motorcycles': typeof AppDailyBodaMotorcyclesRoute
  '/daily-boda/payments': typeof AppDailyBodaPaymentsRoute
  '/loans/$id': typeof AppLoansIdRoute
  '/loans/new': typeof AppLoansNewRoute
  '/motorcycles/$id': typeof AppMotorcyclesIdRoute
  '/products/$id': typeof AppProductsIdRoute
  '/products/new': typeof AppProductsNewRoute
  '/reports/cashiers': typeof AppReportsCashiersRoute
  '/reports/collections': typeof AppReportsCollectionsRoute
  '/reports/daily': typeof AppReportsDailyRoute
  '/reports/daily-boda': typeof AppReportsDailyBodaRoute
  '/reports/loans': typeof AppReportsLoansRoute
  '/reports/motorcycles': typeof AppReportsMotorcyclesRoute
  '/reports/performance': typeof AppReportsPerformanceRoute
  '/reports/pnl': typeof AppReportsPnlRoute
  '/reports/stock': typeof AppReportsStockRoute
  '/sales/$id': typeof AppSalesIdRoute
  '/staff/invite': typeof AppStaffInviteRoute
  '/stock/in': typeof AppStockInRoute
  '/stock/movements': typeof AppStockMovementsRoute
  '/stock/transfer': typeof AppStockTransferRoute
  '/system/observability': typeof AppSystemObservabilityRoute
  '/system/security': typeof AppSystemSecurityRoute
  '/borrowers': typeof AppBorrowersIndexRoute
  '/branches': typeof AppBranchesIndexRoute
  '/cash-sales': typeof AppCashSalesIndexRoute
  '/loan-products': typeof AppLoanProductsIndexRoute
  '/loans': typeof AppLoansIndexRoute
  '/motorcycles': typeof AppMotorcyclesIndexRoute
  '/products': typeof AppProductsIndexRoute
  '/repayments': typeof AppRepaymentsIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/sales': typeof AppSalesIndexRoute
  '/staff': typeof AppStaffIndexRoute
  '/stock': typeof AppStockIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/activities': typeof AppActivitiesRoute
  '/_app/loans-overview': typeof AppLoansOverviewRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/spares': typeof AppSparesRoute
  '/_auth/login': typeof AuthLoginRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/borrowers/$id': typeof AppBorrowersIdRoute
  '/_app/branches/new': typeof AppBranchesNewRoute
  '/_app/cash-sales/$id': typeof AppCashSalesIdRoute
  '/_app/cash-sales/new': typeof AppCashSalesNewRoute
  '/_app/daily-boda/drivers': typeof AppDailyBodaDriversRoute
  '/_app/daily-boda/motorcycles': typeof AppDailyBodaMotorcyclesRoute
  '/_app/daily-boda/payments': typeof AppDailyBodaPaymentsRoute
  '/_app/loans/$id': typeof AppLoansIdRoute
  '/_app/loans/new': typeof AppLoansNewRoute
  '/_app/motorcycles/$id': typeof AppMotorcyclesIdRoute
  '/_app/products/$id': typeof AppProductsIdRoute
  '/_app/products/new': typeof AppProductsNewRoute
  '/_app/reports/cashiers': typeof AppReportsCashiersRoute
  '/_app/reports/collections': typeof AppReportsCollectionsRoute
  '/_app/reports/daily': typeof AppReportsDailyRoute
  '/_app/reports/daily-boda': typeof AppReportsDailyBodaRoute
  '/_app/reports/loans': typeof AppReportsLoansRoute
  '/_app/reports/motorcycles': typeof AppReportsMotorcyclesRoute
  '/_app/reports/performance': typeof AppReportsPerformanceRoute
  '/_app/reports/pnl': typeof AppReportsPnlRoute
  '/_app/reports/stock': typeof AppReportsStockRoute
  '/_app/sales/$id': typeof AppSalesIdRoute
  '/_app/staff/invite': typeof AppStaffInviteRoute
  '/_app/stock/in': typeof AppStockInRoute
  '/_app/stock/movements': typeof AppStockMovementsRoute
  '/_app/stock/transfer': typeof AppStockTransferRoute
  '/_app/system/observability': typeof AppSystemObservabilityRoute
  '/_app/system/security': typeof AppSystemSecurityRoute
  '/_app/borrowers/': typeof AppBorrowersIndexRoute
  '/_app/branches/': typeof AppBranchesIndexRoute
  '/_app/cash-sales/': typeof AppCashSalesIndexRoute
  '/_app/loan-products/': typeof AppLoanProductsIndexRoute
  '/_app/loans/': typeof AppLoansIndexRoute
  '/_app/motorcycles/': typeof AppMotorcyclesIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
  '/_app/repayments/': typeof AppRepaymentsIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/sales/': typeof AppSalesIndexRoute
  '/_app/staff/': typeof AppStaffIndexRoute
  '/_app/stock/': typeof AppStockIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/loans-overview'
    | '/pos'
    | '/settings'
    | '/spares'
    | '/login'
    | '/invite/$token'
    | '/borrowers/$id'
    | '/branches/new'
    | '/cash-sales/$id'
    | '/cash-sales/new'
    | '/daily-boda/drivers'
    | '/daily-boda/motorcycles'
    | '/daily-boda/payments'
    | '/loans/$id'
    | '/loans/new'
    | '/motorcycles/$id'
    | '/products/$id'
    | '/products/new'
    | '/reports/cashiers'
    | '/reports/collections'
    | '/reports/daily'
    | '/reports/daily-boda'
    | '/reports/loans'
    | '/reports/motorcycles'
    | '/reports/performance'
    | '/reports/pnl'
    | '/reports/stock'
    | '/sales/$id'
    | '/staff/invite'
    | '/stock/in'
    | '/stock/movements'
    | '/stock/transfer'
    | '/system/observability'
    | '/system/security'
    | '/borrowers/'
    | '/branches/'
    | '/cash-sales/'
    | '/loan-products/'
    | '/loans/'
    | '/motorcycles/'
    | '/products/'
    | '/repayments/'
    | '/reports/'
    | '/sales/'
    | '/staff/'
    | '/stock/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/loans-overview'
    | '/pos'
    | '/settings'
    | '/spares'
    | '/login'
    | '/invite/$token'
    | '/borrowers/$id'
    | '/branches/new'
    | '/cash-sales/$id'
    | '/cash-sales/new'
    | '/daily-boda/drivers'
    | '/daily-boda/motorcycles'
    | '/daily-boda/payments'
    | '/loans/$id'
    | '/loans/new'
    | '/motorcycles/$id'
    | '/products/$id'
    | '/products/new'
    | '/reports/cashiers'
    | '/reports/collections'
    | '/reports/daily'
    | '/reports/daily-boda'
    | '/reports/loans'
    | '/reports/motorcycles'
    | '/reports/performance'
    | '/reports/pnl'
    | '/reports/stock'
    | '/sales/$id'
    | '/staff/invite'
    | '/stock/in'
    | '/stock/movements'
    | '/stock/transfer'
    | '/system/observability'
    | '/system/security'
    | '/borrowers'
    | '/branches'
    | '/cash-sales'
    | '/loan-products'
    | '/loans'
    | '/motorcycles'
    | '/products'
    | '/repayments'
    | '/reports'
    | '/sales'
    | '/staff'
    | '/stock'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/activities'
    | '/_app/loans-overview'
    | '/_app/pos'
    | '/_app/settings'
    | '/_app/spares'
    | '/_auth/login'
    | '/invite/$token'
    | '/_app/'
    | '/_app/borrowers/$id'
    | '/_app/branches/new'
    | '/_app/cash-sales/$id'
    | '/_app/cash-sales/new'
    | '/_app/daily-boda/drivers'
    | '/_app/daily-boda/motorcycles'
    | '/_app/daily-boda/payments'
    | '/_app/loans/$id'
    | '/_app/loans/new'
    | '/_app/motorcycles/$id'
    | '/_app/products/$id'
    | '/_app/products/new'
    | '/_app/reports/cashiers'
    | '/_app/reports/collections'
    | '/_app/reports/daily'
    | '/_app/reports/daily-boda'
    | '/_app/reports/loans'
    | '/_app/reports/motorcycles'
    | '/_app/reports/performance'
    | '/_app/reports/pnl'
    | '/_app/reports/stock'
    | '/_app/sales/$id'
    | '/_app/staff/invite'
    | '/_app/stock/in'
    | '/_app/stock/movements'
    | '/_app/stock/transfer'
    | '/_app/system/observability'
    | '/_app/system/security'
    | '/_app/borrowers/'
    | '/_app/branches/'
    | '/_app/cash-sales/'
    | '/_app/loan-products/'
    | '/_app/loans/'
    | '/_app/motorcycles/'
    | '/_app/products/'
    | '/_app/repayments/'
    | '/_app/reports/'
    | '/_app/sales/'
    | '/_app/staff/'
    | '/_app/stock/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/spares': {
      id: '/_app/spares'
      path: '/spares'
      fullPath: '/spares'
      preLoaderRoute: typeof AppSparesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans-overview': {
      id: '/_app/loans-overview'
      path: '/loans-overview'
      fullPath: '/loans-overview'
      preLoaderRoute: typeof AppLoansOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activities': {
      id: '/_app/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AppActivitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock/': {
      id: '/_app/stock/'
      path: '/stock'
      fullPath: '/stock/'
      preLoaderRoute: typeof AppStockIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff/': {
      id: '/_app/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof AppStaffIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/': {
      id: '/_app/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof AppSalesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repayments/': {
      id: '/_app/repayments/'
      path: '/repayments'
      fullPath: '/repayments/'
      preLoaderRoute: typeof AppRepaymentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/motorcycles/': {
      id: '/_app/motorcycles/'
      path: '/motorcycles'
      fullPath: '/motorcycles/'
      preLoaderRoute: typeof AppMotorcyclesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans/': {
      id: '/_app/loans/'
      path: '/loans'
      fullPath: '/loans/'
      preLoaderRoute: typeof AppLoansIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loan-products/': {
      id: '/_app/loan-products/'
      path: '/loan-products'
      fullPath: '/loan-products/'
      preLoaderRoute: typeof AppLoanProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cash-sales/': {
      id: '/_app/cash-sales/'
      path: '/cash-sales'
      fullPath: '/cash-sales/'
      preLoaderRoute: typeof AppCashSalesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/branches/': {
      id: '/_app/branches/'
      path: '/branches'
      fullPath: '/branches/'
      preLoaderRoute: typeof AppBranchesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/borrowers/': {
      id: '/_app/borrowers/'
      path: '/borrowers'
      fullPath: '/borrowers/'
      preLoaderRoute: typeof AppBorrowersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system/security': {
      id: '/_app/system/security'
      path: '/system/security'
      fullPath: '/system/security'
      preLoaderRoute: typeof AppSystemSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system/observability': {
      id: '/_app/system/observability'
      path: '/system/observability'
      fullPath: '/system/observability'
      preLoaderRoute: typeof AppSystemObservabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock/transfer': {
      id: '/_app/stock/transfer'
      path: '/stock/transfer'
      fullPath: '/stock/transfer'
      preLoaderRoute: typeof AppStockTransferRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock/movements': {
      id: '/_app/stock/movements'
      path: '/stock/movements'
      fullPath: '/stock/movements'
      preLoaderRoute: typeof AppStockMovementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stock/in': {
      id: '/_app/stock/in'
      path: '/stock/in'
      fullPath: '/stock/in'
      preLoaderRoute: typeof AppStockInRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff/invite': {
      id: '/_app/staff/invite'
      path: '/staff/invite'
      fullPath: '/staff/invite'
      preLoaderRoute: typeof AppStaffInviteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/$id': {
      id: '/_app/sales/$id'
      path: '/sales/$id'
      fullPath: '/sales/$id'
      preLoaderRoute: typeof AppSalesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/stock': {
      id: '/_app/reports/stock'
      path: '/reports/stock'
      fullPath: '/reports/stock'
      preLoaderRoute: typeof AppReportsStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/pnl': {
      id: '/_app/reports/pnl'
      path: '/reports/pnl'
      fullPath: '/reports/pnl'
      preLoaderRoute: typeof AppReportsPnlRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/performance': {
      id: '/_app/reports/performance'
      path: '/reports/performance'
      fullPath: '/reports/performance'
      preLoaderRoute: typeof AppReportsPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/motorcycles': {
      id: '/_app/reports/motorcycles'
      path: '/reports/motorcycles'
      fullPath: '/reports/motorcycles'
      preLoaderRoute: typeof AppReportsMotorcyclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/loans': {
      id: '/_app/reports/loans'
      path: '/reports/loans'
      fullPath: '/reports/loans'
      preLoaderRoute: typeof AppReportsLoansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/daily-boda': {
      id: '/_app/reports/daily-boda'
      path: '/reports/daily-boda'
      fullPath: '/reports/daily-boda'
      preLoaderRoute: typeof AppReportsDailyBodaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/daily': {
      id: '/_app/reports/daily'
      path: '/reports/daily'
      fullPath: '/reports/daily'
      preLoaderRoute: typeof AppReportsDailyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/collections': {
      id: '/_app/reports/collections'
      path: '/reports/collections'
      fullPath: '/reports/collections'
      preLoaderRoute: typeof AppReportsCollectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/cashiers': {
      id: '/_app/reports/cashiers'
      path: '/reports/cashiers'
      fullPath: '/reports/cashiers'
      preLoaderRoute: typeof AppReportsCashiersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/new': {
      id: '/_app/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AppProductsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/$id': {
      id: '/_app/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AppProductsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/motorcycles/$id': {
      id: '/_app/motorcycles/$id'
      path: '/motorcycles/$id'
      fullPath: '/motorcycles/$id'
      preLoaderRoute: typeof AppMotorcyclesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans/new': {
      id: '/_app/loans/new'
      path: '/loans/new'
      fullPath: '/loans/new'
      preLoaderRoute: typeof AppLoansNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans/$id': {
      id: '/_app/loans/$id'
      path: '/loans/$id'
      fullPath: '/loans/$id'
      preLoaderRoute: typeof AppLoansIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/daily-boda/payments': {
      id: '/_app/daily-boda/payments'
      path: '/daily-boda/payments'
      fullPath: '/daily-boda/payments'
      preLoaderRoute: typeof AppDailyBodaPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/daily-boda/motorcycles': {
      id: '/_app/daily-boda/motorcycles'
      path: '/daily-boda/motorcycles'
      fullPath: '/daily-boda/motorcycles'
      preLoaderRoute: typeof AppDailyBodaMotorcyclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/daily-boda/drivers': {
      id: '/_app/daily-boda/drivers'
      path: '/daily-boda/drivers'
      fullPath: '/daily-boda/drivers'
      preLoaderRoute: typeof AppDailyBodaDriversRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cash-sales/new': {
      id: '/_app/cash-sales/new'
      path: '/cash-sales/new'
      fullPath: '/cash-sales/new'
      preLoaderRoute: typeof AppCashSalesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cash-sales/$id': {
      id: '/_app/cash-sales/$id'
      path: '/cash-sales/$id'
      fullPath: '/cash-sales/$id'
      preLoaderRoute: typeof AppCashSalesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/branches/new': {
      id: '/_app/branches/new'
      path: '/branches/new'
      fullPath: '/branches/new'
      preLoaderRoute: typeof AppBranchesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/borrowers/$id': {
      id: '/_app/borrowers/$id'
      path: '/borrowers/$id'
      fullPath: '/borrowers/$id'
      preLoaderRoute: typeof AppBorrowersIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivitiesRoute: typeof AppActivitiesRoute
  AppLoansOverviewRoute: typeof AppLoansOverviewRoute
  AppPosRoute: typeof AppPosRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSparesRoute: typeof AppSparesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBorrowersIdRoute: typeof AppBorrowersIdRoute
  AppBranchesNewRoute: typeof AppBranchesNewRoute
  AppCashSalesIdRoute: typeof AppCashSalesIdRoute
  AppCashSalesNewRoute: typeof AppCashSalesNewRoute
  AppDailyBodaDriversRoute: typeof AppDailyBodaDriversRoute
  AppDailyBodaMotorcyclesRoute: typeof AppDailyBodaMotorcyclesRoute
  AppDailyBodaPaymentsRoute: typeof AppDailyBodaPaymentsRoute
  AppLoansIdRoute: typeof AppLoansIdRoute
  AppLoansNewRoute: typeof AppLoansNewRoute
  AppMotorcyclesIdRoute: typeof AppMotorcyclesIdRoute
  AppProductsIdRoute: typeof AppProductsIdRoute
  AppProductsNewRoute: typeof AppProductsNewRoute
  AppReportsCashiersRoute: typeof AppReportsCashiersRoute
  AppReportsCollectionsRoute: typeof AppReportsCollectionsRoute
  AppReportsDailyRoute: typeof AppReportsDailyRoute
  AppReportsDailyBodaRoute: typeof AppReportsDailyBodaRoute
  AppReportsLoansRoute: typeof AppReportsLoansRoute
  AppReportsMotorcyclesRoute: typeof AppReportsMotorcyclesRoute
  AppReportsPerformanceRoute: typeof AppReportsPerformanceRoute
  AppReportsPnlRoute: typeof AppReportsPnlRoute
  AppReportsStockRoute: typeof AppReportsStockRoute
  AppSalesIdRoute: typeof AppSalesIdRoute
  AppStaffInviteRoute: typeof AppStaffInviteRoute
  AppStockInRoute: typeof AppStockInRoute
  AppStockMovementsRoute: typeof AppStockMovementsRoute
  AppStockTransferRoute: typeof AppStockTransferRoute
  AppSystemObservabilityRoute: typeof AppSystemObservabilityRoute
  AppSystemSecurityRoute: typeof AppSystemSecurityRoute
  AppBorrowersIndexRoute: typeof AppBorrowersIndexRoute
  AppBranchesIndexRoute: typeof AppBranchesIndexRoute
  AppCashSalesIndexRoute: typeof AppCashSalesIndexRoute
  AppLoanProductsIndexRoute: typeof AppLoanProductsIndexRoute
  AppLoansIndexRoute: typeof AppLoansIndexRoute
  AppMotorcyclesIndexRoute: typeof AppMotorcyclesIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
  AppRepaymentsIndexRoute: typeof AppRepaymentsIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppSalesIndexRoute: typeof AppSalesIndexRoute
  AppStaffIndexRoute: typeof AppStaffIndexRoute
  AppStockIndexRoute: typeof AppStockIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivitiesRoute: AppActivitiesRoute,
  AppLoansOverviewRoute: AppLoansOverviewRoute,
  AppPosRoute: AppPosRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSparesRoute: AppSparesRoute,
  AppIndexRoute: AppIndexRoute,
  AppBorrowersIdRoute: AppBorrowersIdRoute,
  AppBranchesNewRoute: AppBranchesNewRoute,
  AppCashSalesIdRoute: AppCashSalesIdRoute,
  AppCashSalesNewRoute: AppCashSalesNewRoute,
  AppDailyBodaDriversRoute: AppDailyBodaDriversRoute,
  AppDailyBodaMotorcyclesRoute: AppDailyBodaMotorcyclesRoute,
  AppDailyBodaPaymentsRoute: AppDailyBodaPaymentsRoute,
  AppLoansIdRoute: AppLoansIdRoute,
  AppLoansNewRoute: AppLoansNewRoute,
  AppMotorcyclesIdRoute: AppMotorcyclesIdRoute,
  AppProductsIdRoute: AppProductsIdRoute,
  AppProductsNewRoute: AppProductsNewRoute,
  AppReportsCashiersRoute: AppReportsCashiersRoute,
  AppReportsCollectionsRoute: AppReportsCollectionsRoute,
  AppReportsDailyRoute: AppReportsDailyRoute,
  AppReportsDailyBodaRoute: AppReportsDailyBodaRoute,
  AppReportsLoansRoute: AppReportsLoansRoute,
  AppReportsMotorcyclesRoute: AppReportsMotorcyclesRoute,
  AppReportsPerformanceRoute: AppReportsPerformanceRoute,
  AppReportsPnlRoute: AppReportsPnlRoute,
  AppReportsStockRoute: AppReportsStockRoute,
  AppSalesIdRoute: AppSalesIdRoute,
  AppStaffInviteRoute: AppStaffInviteRoute,
  AppStockInRoute: AppStockInRoute,
  AppStockMovementsRoute: AppStockMovementsRoute,
  AppStockTransferRoute: AppStockTransferRoute,
  AppSystemObservabilityRoute: AppSystemObservabilityRoute,
  AppSystemSecurityRoute: AppSystemSecurityRoute,
  AppBorrowersIndexRoute: AppBorrowersIndexRoute,
  AppBranchesIndexRoute: AppBranchesIndexRoute,
  AppCashSalesIndexRoute: AppCashSalesIndexRoute,
  AppLoanProductsIndexRoute: AppLoanProductsIndexRoute,
  AppLoansIndexRoute: AppLoansIndexRoute,
  AppMotorcyclesIndexRoute: AppMotorcyclesIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
  AppRepaymentsIndexRoute: AppRepaymentsIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppSalesIndexRoute: AppSalesIndexRoute,
  AppStaffIndexRoute: AppStaffIndexRoute,
  AppStockIndexRoute: AppStockIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
