import { CodeBlock } from '@/components/code-block'
import { TipBox } from '@/components/course/tip-box'
import { Exercise } from '@/components/course/exercise'
import { KnowledgeCheck } from '@/components/course/knowledge-check'

export default function Lesson() {
  return (
    <>
      <p>
        <code>packages/shared</code> is the glue. Zod schemas, generated TS
        types, route constants — anything web and admin both need. One
        source of truth; the two apps stay aligned forever.
      </p>

      <h2>What lives in it</h2>
      <CodeBlock
        language="text"
        filename="packages/shared/src/"
        code={`packages/shared/src/
├── schemas/                  Zod schemas — both apps validate the same way
│   ├── user.ts
│   ├── auth.ts
│   └── product.ts
├── types/                    TypeScript types — generated by grit sync
│   ├── user.ts               from internal/models/user.go
│   ├── product.ts            from internal/models/product.go
│   └── index.ts
├── constants/                shared constants
│   ├── routes.ts             API path constants used by both apps
│   ├── roles.ts              UserRole = "user" | "staff" | "admin"
│   └── plans.ts
└── index.ts                  re-exports everything`}
      />

      <h2>Importing into web / admin</h2>
      <CodeBlock
        language="ts"
        filename="apps/web/components/login-form.tsx"
        code={`import { LoginSchema } from '@workspace/shared/schemas/auth'
import type { User } from '@workspace/shared/types/user'
import { API_ROUTES } from '@workspace/shared/constants/routes'

// LoginSchema validates the form input.
// User typed the response.
// API_ROUTES gives '/api/auth/login' as a constant — no typos.`}
      />
      <p>
        Importing from <code>@workspace/shared</code> uses pnpm&apos;s
        workspace symlinks. TypeScript follows the symlink and resolves
        types correctly. No build step needed.
      </p>

      <h2>The grit sync round-trip</h2>
      <p>
        Reminder from earlier courses: when you change a Go struct, run{' '}
        <code>grit sync</code> to regenerate <code>packages/shared/src/types/</code>.
        Both apps pick up the new types instantly.
      </p>
      <CodeBlock
        terminal
        code={`# After editing apps/api/internal/models/user.go
grit sync
# Now web + admin both see the new field`}
      />

      <h2>Why not just publish to npm?</h2>
      <p>
        You could. But the workspace pattern means changes propagate
        instantly without a publish cycle. Edit a schema; both apps see it
        on next reload. For internal types this is ideal.
      </p>
      <p>
        When you graduate to public types (SDK for third parties), THEN
        publish to npm — but for internal monorepo work, workspaces win.
      </p>

      <TipBox tone="success">
        <strong>Constants beat magic strings.</strong> Every API path lives in{' '}
        <code>constants/routes.ts</code>. <code>API_ROUTES.AUTH_LOGIN</code>{' '}
        beats <code>&apos;/api/auth/login&apos;</code> sprinkled across 12 files.
        Rename once, references update.
      </TipBox>

      <h2>What NOT to put in shared</h2>
      <ul>
        <li>
          <strong>React components</strong> — they belong in{' '}
          <code>apps/web/components/</code> or <code>apps/admin/components/</code>{' '}
          (or a separate <code>packages/ui</code> if you want a design
          system).
        </li>
        <li>
          <strong>App-specific business logic</strong> — that should stay
          in the relevant app.
        </li>
        <li>
          <strong>Anything that imports from <code>apps/*</code></strong> — would
          create circular dependencies.
        </li>
      </ul>

      <KnowledgeCheck
        question="You need a `formatCurrency()` helper used by web (price display) AND admin (totals). Where does it go?"
        choices={[
          {
            label: 'apps/web/lib/format.ts and copy to apps/admin/lib/format.ts',
            feedback:
              "Two copies that will drift. The whole point of shared is to prevent this.",
          },
          {
            label: 'packages/shared/src/utils/format.ts — both apps import it',
            correct: true,
            feedback:
              "Right — pure functions used by both apps live in shared. Add a tests/ next to it; same tests benefit both apps.",
          },
          {
            label: 'apps/api/internal/helpers/format.go and call it via API',
            feedback:
              "Wildly over-engineered. A formatter is local, pure, fast. Calling the API for currency formatting would be madness.",
          },
          {
            label: 'A new packages/ui package',
            feedback:
              "Reasonable if you're building a full design system, but for one util function, shared/utils is enough.",
          },
        ]}
      />

      <Exercise
        prompt={
          <>
            <p>
              Add a <code>formatCurrency()</code> helper to{' '}
              <code>packages/shared</code>:
            </p>
            <ol>
              <li>
                Create{' '}
                <code>packages/shared/src/utils/currency.ts</code> exporting{' '}
                <code>formatCurrency(amount: number): string</code>.
              </li>
              <li>
                Import it into <code>apps/web/app/(app)/dashboard/page.tsx</code>{' '}
                and use it to render a price.
              </li>
              <li>
                Import the same function into one admin page.
              </li>
              <li>
                In <code>notes.md</code>, paste both import statements +
                where you used it.
              </li>
            </ol>
            <p>That completes chapter 1&apos;s assignment.</p>
          </>
        }
        hint={
          <>
            Use <code>Intl.NumberFormat('en-US', {`{ style: 'currency', currency: 'USD' }`}).format(amount)</code>{' '}
            in one line.
          </>
        }
        solution={
          <>
            <CodeBlock
              language="ts"
              filename="packages/shared/src/utils/currency.ts"
              code={`export function formatCurrency(amount: number, currency = 'USD'): string {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency }).format(amount)
}`}
            />
            <p>Both apps now have a single, consistent way to format money.</p>
          </>
        }
      />

      <h2>What&apos;s next</h2>
      <p>
        Chapter 2 — <strong>The Public Site</strong>. Landing page, marketing
        pages, SEO + Open Graph. The customer-facing surface.
      </p>
    </>
  )
}
