import Link from "next/link";
import { ArrowRight, ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SiteHeader } from "@/components/site-header";
import { DocsSidebar } from "@/components/docs-sidebar";
import { CodeBlock } from "@/components/code-block";
import { LaneFlow } from "@/components/lane-flow";
import { getDocMetadata } from '@/config/docs-metadata'

export const metadata = getDocMetadata('/docs/batteries/email')

const code = "text-xs font-mono bg-accent/50 px-1.5 py-0.5 rounded";

const drivers: { name: string; how: string; env: string }[] = [
  { name: "smtp", how: "net/smtp with STARTTLS or implicit TLS, MIME multipart. Unset, it is Mailhog on localhost:1025.", env: "SMTP_HOST, SMTP_PORT, SMTP_USERNAME, SMTP_PASSWORD, SMTP_ENCRYPTION" },
  { name: "resend", how: "Resend's HTTP API.", env: "RESEND_API_KEY" },
  { name: "mailgun", how: "Mailgun's messages API, US or EU endpoint.", env: "MAILGUN_DOMAIN, MAILGUN_SECRET, MAILGUN_ENDPOINT" },
  { name: "postmark", how: "Postmark's email API.", env: "POSTMARK_TOKEN, POSTMARK_MESSAGE_STREAM" },
  { name: "sendgrid", how: "SendGrid's v3 Mail Send API.", env: "SENDGRID_API_KEY" },
  { name: "ses", how: "Amazon SES API v2, signed with SigV4. No AWS SDK.", env: "AWS_SES_REGION, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY" },
  { name: "log", how: "Writes each message to the log and to storage/mail. Refused in production unless MAIL_ALLOW_LOG_IN_PRODUCTION=true.", env: "MAIL_LOG_PATH" },
  { name: "failover", how: "Tries each driver in MAIL_FAILOVER in order, logging every failure.", env: "MAIL_FAILOVER" },
];

export default function EmailPage() {
  return (
    <div className="min-h-screen bg-background isolate">
      <SiteHeader />
      <DocsSidebar />

      <main className="lg:pl-64">
        <div className="container max-w-screen-xl py-10 px-6">
          <div className="max-w-3xl">
            {/* Header */}
            <div className="mb-10">
              <span className="tag-mono text-primary/80 mb-3 block">
                Batteries
              </span>
              <h1 className="text-4xl font-bold tracking-tight mb-4">
                Email System
              </h1>
              <p className="text-lg text-muted-foreground leading-relaxed">
                Every Grit API sends mail through{" "}
                <code className={code}>internal/mail</code>: one Mailer over a
                Transport, with SMTP, Resend, Mailgun, Postmark, SendGrid, SES,
                log and failover drivers, all on the standard library. The code
                that sends mail does not change when the provider does. Messages
                can go out now or through the background queue, templates are
                typed Go generated by{" "}
                <code className={code}>grit generate mail</code>, and the admin
                previews them as the API renders them.
              </p>
              <LaneFlow
                id="bat-email"
                lanes={['Your code', 'internal/mail', 'Delivery']}
                nodes={[
                  { id: 'send', lane: 0, row: 0, title: 'SendOrderShipped()', sub: 'typed data', tone: 'primary' },
                  { id: 'queue', lane: 0, row: 1, title: 'mail.Queue()', sub: 'email:send job', tone: 'primary' },
                  { id: 'mailer', lane: 1, row: 0, title: 'Mailer', sub: 'layout + text part', tone: 'cyan' },
                  { id: 'worker', lane: 1, row: 1, title: 'Worker', sub: 'retries with backoff', tone: 'cyan' },
                  { id: 'driver', lane: 2, row: 0, title: 'MAIL_MAILER', sub: 'smtp, resend, ses...', tone: 'violet' },
                  { id: 'inbox', lane: 2, row: 1, title: 'Inbox', sub: 'or Mailhog in dev', tone: 'green' },
                ]}
                edges={[
                  { from: 'send', to: 'mailer', label: 'now', tone: 'cyan' },
                  { from: 'queue', to: 'worker', label: 'Redis', tone: 'cyan' },
                  { from: 'worker', to: 'mailer', label: 'SendMessage', tone: 'cyan' },
                  { from: 'mailer', to: 'driver', label: 'Transport', tone: 'violet' },
                  { from: 'driver', to: 'inbox', label: 'deliver', tone: 'green' },
                ]}
                legend={[
                  { tone: 'cyan', label: 'Rendering and queueing' },
                  { tone: 'violet', label: 'The configured driver' },
                ]}
                caption="Send now or queue for the worker; either way the Mailer hands the message to the driver MAIL_MAILER names"
              />
            </div>

            <div className="prose-grit">
              {/* Drivers */}
              <div className="mb-12">
                <h2 className="text-2xl font-semibold tracking-tight mb-4">
                  Drivers and configuration
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  <code className={code}>MAIL_MAILER</code> names the driver,
                  and <code className={code}>mail.FromConfig</code> builds it
                  once at startup in <code className={code}>main.go</code>.
                  Left empty, a real <code className={code}>RESEND_API_KEY</code>{" "}
                  means Resend, which is how projects sent mail before there
                  were drivers. With neither, development sends to Mailhog and
                  falls back to the log, so a reset link is never lost, and
                  production has no mailer and says so at startup. A driver that
                  is named but not configured stops the API from starting rather
                  than quietly sending somewhere else.
                </p>

                <div className="rounded-lg border border-border/30 bg-card/30 overflow-x-auto mb-6">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="border-b border-border/30 bg-accent/20">
                        <th className="text-left px-4 py-2.5 font-medium text-foreground/80">Driver</th>
                        <th className="text-left px-4 py-2.5 font-medium text-foreground/80">How it sends</th>
                        <th className="text-left px-4 py-2.5 font-medium text-foreground/80">Keys</th>
                      </tr>
                    </thead>
                    <tbody className="text-muted-foreground">
                      {drivers.map((d) => (
                        <tr key={d.name} className="border-b border-border/20 last:border-0">
                          <td className="px-4 py-2.5 font-mono text-xs">{d.name}</td>
                          <td className="px-4 py-2.5">{d.how}</td>
                          <td className="px-4 py-2.5 font-mono text-xs">{d.env}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>

                <CodeBlock language="bash" filename=".env" code={`# Common to every driver
MAIL_MAILER=smtp
MAIL_FROM=noreply@yourdomain.com
MAIL_FROM_NAME=My App

# SMTP. SMTP_ENCRYPTION is tls, starttls or none; empty means tls on
# port 465, none for localhost and starttls for anything else.
SMTP_HOST=smtp.yourprovider.com
SMTP_PORT=587
SMTP_USERNAME=apikey
SMTP_PASSWORD=your-password

# Or try one driver, then the next
# MAIL_MAILER=failover
# MAIL_FAILOVER=postmark,smtp`} />

                <p className="text-muted-foreground leading-relaxed mt-4">
                  The HTTP drivers share one client with a 15 second timeout,
                  retry once on a network error or a 5xx, and never retry a 4xx,
                  which is the provider saying the message itself is wrong.{" "}
                  <code className={code}>/api/health</code> reports the driver in
                  use, and the admin&apos;s System Health page shows it.
                </p>
              </div>

              {/* Mailhog */}
              <div className="mb-12">
                <h2 className="text-2xl font-semibold tracking-tight mb-4">
                  Development mail with Mailhog
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  <code className={code}>docker compose up -d</code> starts
                  Mailhog beside Postgres and Redis. With no driver configured,
                  development mail goes to it over SMTP on{" "}
                  <code className={code}>MAILHOG_SMTP_PORT</code>, and its inbox
                  is on <code className={code}>MAILHOG_UI_PORT</code>. When Mailhog
                  is not running the message is written to{" "}
                  <code className={code}>storage/mail</code> and the log instead.
                </p>
              </div>

              {/* Sending */}
              <div className="mb-12">
                <h2 className="text-2xl font-semibold tracking-tight mb-4">
                  Sending now
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  <code className={code}>SendMessage</code> takes any message:
                  several recipients, cc, bcc, reply-to, a text part, attachments
                  and headers. <code className={code}>Send</code> and{" "}
                  <code className={code}>SendRaw</code> keep the signatures they
                  always had. Password resets, email verification and recovery
                  codes are sent this way, because the person is waiting for
                  them and a failure should show while they are there.
                </p>

                <CodeBlock language="go" filename="internal/services/invoice.go" code={`err := mailer.SendMessage(ctx, &mail.Message{
    To:      []string{customer.Email},
    Cc:      []string{"accounts@example.com"},
    ReplyTo: "billing@example.com",
    Subject: "Invoice INV-001",
    HTML:    "<p>Your invoice is attached.</p>",
    Text:    "Your invoice is attached.",
    Attachments: []mail.Attachment{
        {Filename: "INV-001.pdf", ContentType: "application/pdf", Content: pdf},
    },
})

// A built-in template with its data
err = mailer.Send(ctx, mail.SendOptions{
    To:       user.Email,
    Subject:  "Welcome",
    Template: "welcome",
    Data:     map[string]interface{}{"AppName": cfg.AppName, "Name": user.FirstName},
})`} />
              </div>

              {/* Queueing */}
              <div className="mb-12">
                <h2 className="text-2xl font-semibold tracking-tight mb-4">
                  Queueing
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  <code className={code}>mail.Queue</code> puts the whole message
                  on the <code className={code}>email:send</code> background job.
                  The request returns without waiting for the provider, and the
                  worker sends it with the same Mailer, retrying with exponential
                  backoff. Queue checks the message first, so a missing recipient
                  or a header with a line break fails in the request, not in the
                  worker later.
                </p>

                <CodeBlock language="go" filename="internal/handlers/orders.go" code={`// svc.Jobs is the *jobs.Client main.go builds when Redis is reachable.
if err := mail.Queue(ctx, svc.Jobs, &mail.Message{
    To:      []string{order.Email},
    Subject: "Order confirmed",
    HTML:    html,
    Text:    text,
}); err != nil {
    return fmt.Errorf("queueing the confirmation: %w", err)
}`} />

                <div className="p-4 rounded-lg border border-primary/20 bg-primary/5 mt-4">
                  <p className="text-sm text-foreground/80">
                    <strong>Attachments are capped at 256 KB when queued.</strong>{" "}
                    The message waits in Redis and is stored again for every retry,
                    so <code className={code}>mail.Queue</code> refuses larger
                    attachments with <code className={code}>mail.ErrAttachmentsTooLarge</code>.
                    Upload the file to storage and send a link to it instead.
                  </p>
                </div>
              </div>

              {/* Generator */}
              <div className="mb-12">
                <h2 className="text-2xl font-semibold tracking-tight mb-4">
                  Writing your own email
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  The generator writes one file in{" "}
                  <code className={code}>internal/mail/templates</code>: a typed
                  data struct, an <code className={code}>html/template</code> body
                  inside the shared layout (the app name, the card and the footer),
                  a plain-text alternative, and helpers to render, send and queue
                  it. The file registers the email for the admin&apos;s Mail
                  Preview. It is yours from then on, and a second generate refuses
                  to overwrite it.
                </p>

                <CodeBlock language="bash" code={`grit generate mail OrderShipped`} />

                <CodeBlock language="go" filename="internal/mail/templates/order_shipped.go (abridged)" code={`type OrderShippedData struct {
    AppName   string // empty uses APP_NAME
    Name      string
    ActionURL string
}

const OrderShippedSubject = "Order shipped"

func RenderOrderShipped(data OrderShippedData) (*mail.Message, error)
func SendOrderShipped(ctx context.Context, m *mail.Mailer, to string, data OrderShippedData) error
func QueueOrderShipped(ctx context.Context, q mail.Enqueuer, to string, data OrderShippedData) error`} />

                <CodeBlock language="go" filename="using it" code={`err := templates.SendOrderShipped(ctx, svc.Mailer, order.Email, templates.OrderShippedData{
    Name:      order.CustomerName,
    ActionURL: "https://shop.example.com/orders/" + order.ID,
})`} />

                <p className="text-muted-foreground leading-relaxed mt-4">
                  Add fields to the struct and use them in the body; the compiler
                  then checks every call that sends the email. The built-in
                  templates, <code className={code}>welcome</code>,{" "}
                  <code className={code}>password-reset</code>,{" "}
                  <code className={code}>email-verification</code> and{" "}
                  <code className={code}>notification</code>, stay in{" "}
                  <code className={code}>internal/mail/templates.go</code> for{" "}
                  <code className={code}>Mailer.Send</code>.
                </p>
              </div>

              {/* Preview */}
              <div className="mb-12">
                <h2 className="text-2xl font-semibold tracking-tight mb-4">
                  Previewing in the admin
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  <code className={code}>/system/mail</code> lists every
                  registered template and shows it rendered with sample data in a
                  sandboxed frame, with its text part beside it. The page reads
                  two staff routes, both needing{" "}
                  <code className={code}>system.view</code>:
                </p>
                <CodeBlock language="bash" code={`GET /api/admin/mail/templates            # name, description, subject, and the driver in use
GET /api/admin/mail/preview/:template    # the rendered HTML; ?part=text for the text part`} />
              </div>

              {/* Testing */}
              <div className="mb-12">
                <h2 className="text-2xl font-semibold tracking-tight mb-4">
                  Testing with the fake
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  <code className={code}>internal/mail/mailtest</code> is a
                  Transport that records messages instead of sending them. The
                  generated auth tests use it for the reset and verification flows.
                </p>
                <CodeBlock language="go" filename="internal/handlers/orders_test.go" code={`fake := mailtest.New()
h := &OrderHandler{DB: db, Mailer: fake.Mailer()}

// ... exercise the handler ...

msg := fake.AssertSent(t, "ada@example.com", "Order shipped")
if !strings.Contains(msg.Text, "/orders/") {
    t.Errorf("the email has no link to the order")
}

fake.FailWith(errors.New("provider down")) // every later send fails
fake.Reset()
fake.AssertNothingSent(t)`} />
              </div>

              {/* Notifications setting */}
              <div className="mb-10">
                <h2 className="text-2xl font-semibold tracking-tight mb-4">
                  Turning notification mail off
                </h2>
                <p className="text-muted-foreground leading-relaxed mb-4">
                  The <code className={code}>notifications.email_enabled</code>{" "}
                  setting (Settings, Notifications) stops notification emails,
                  such as the new-ticket email to{" "}
                  <code className={code}>SUPPORT_EMAIL</code>, without a deploy.
                  The in-app notifications still arrive. Account mail, password
                  resets and verification, is not affected. See{" "}
                  <Link href="/docs/batteries/jobs" className="text-primary hover:underline">
                    Background Jobs
                  </Link>{" "}
                  for the queue itself.
                </p>
              </div>
            </div>

            {/* Nav */}
            <div className="flex items-center justify-between pt-6 border-t border-border/30">
              <Button
                variant="ghost"
                size="sm"
                asChild
                className="text-muted-foreground/60 hover:text-foreground"
              >
                <Link href="/docs/batteries/storage" className="gap-1.5">
                  <ArrowLeft className="h-3.5 w-3.5" />
                  File Storage
                </Link>
              </Button>
              <Button
                variant="ghost"
                size="sm"
                asChild
                className="text-muted-foreground/60 hover:text-foreground"
              >
                <Link href="/docs/batteries/jobs" className="gap-1.5">
                  Background Jobs
                  <ArrowRight className="h-3.5 w-3.5" />
                </Link>
              </Button>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
