import Link from 'next/link'
import { ArrowRight, ArrowLeft } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { SiteHeader } from '@/components/site-header'
import { DocsSidebar } from '@/components/docs-sidebar'
import { CodeBlock } from '@/components/code-block'
import { getDocMetadata } from '@/config/docs-metadata'

// Generated by scripts/tier-tutorials.py. Edit the table there, not this file.

export const metadata = getDocMetadata('/docs/tutorials/contacts/api')

export default function ContactsApiTutorialPage() {
  return (
    <div className="min-h-screen bg-background isolate">
      <SiteHeader />
      <DocsSidebar />

      <main className="lg:pl-64">
        <div className="container max-w-screen-xl py-10 px-6">
          <div className="max-w-3xl">
            <div className="mb-10">
              <span className="tag-mono text-primary/80 mb-3 block">Tutorial</span>
              <h1 className="text-4xl font-bold tracking-tight mb-4">Contacts: the API on its own</h1>
              <p className="text-lg text-muted-foreground leading-relaxed">When the clients are somebody else&apos;s: a mobile team, a partner integration, or a frontend you have already built. You get the Go API with authentication, migrations, generated reference documentation and nothing else. No Node, no pnpm, no JavaScript anywhere in the project.</p>
            </div>

            <div className="prose-grit">
              <p>
                The app is a contact book: contacts that belong to groups, each with a photo. Two
                resources, two commands, and everything that follows is the same in every tier.
                What differs is what you run and where it ends up, which is what this page is
                about.
              </p>

              <h2>Before you start</h2>
              <ul>
                  <li>
                    <strong>Go 1.21 or newer</strong> &mdash; The only thing this tier needs.
                  </li>
              </ul>
              <p>
                And Grit itself: <code>go install github.com/MUKE-coder/grit/v3/cmd/grit@latest</code>.
              </p>

              <h2>1. Create the project</h2>
              <CodeBlock terminal language="bash" code={`grit new contacts --api --db sqlite
cd contacts`} />
              <p>
                Postgres is the default. <code>--db sqlite</code> above means the project runs
                with no database server at all, which is the shortest path to seeing it work; drop
                the flag when you want Postgres, and <code>docker compose up -d</code> brings one
                up along with Redis, MinIO and a mail catcher.
              </p>

              <table className="w-full text-sm my-6">
                <thead>
                  <tr className="border-b border-border/50 text-left">
                    <th className="px-4 py-2.5 font-medium">Directory</th>
                    <th className="px-4 py-2.5 font-medium">What is in it</th>
                  </tr>
                </thead>
                <tbody>
                  <tr className="border-b border-border/30">
                    <td className="px-4 py-2.5 font-mono text-xs text-primary">apps/api/internal/models</td>
                    <td className="px-4 py-2.5 text-muted-foreground">The Go structs the database is built from</td>
                  </tr>
                  <tr className="border-b border-border/30">
                    <td className="px-4 py-2.5 font-mono text-xs text-primary">apps/api/internal/services</td>
                    <td className="px-4 py-2.5 text-muted-foreground">Where the queries live</td>
                  </tr>
                  <tr className="border-b border-border/30">
                    <td className="px-4 py-2.5 font-mono text-xs text-primary">apps/api/internal/handlers</td>
                    <td className="px-4 py-2.5 text-muted-foreground">Thin HTTP handlers that call the services</td>
                  </tr>
                  <tr className="border-b border-border/30">
                    <td className="px-4 py-2.5 font-mono text-xs text-primary">apps/api/internal/routes</td>
                    <td className="px-4 py-2.5 text-muted-foreground">The route table, and the access registry built from it</td>
                  </tr>
                </tbody>
              </table>

              <h2>2. Describe the data</h2>
              <p>
                A group first, because a contact points at one. Each command writes the Go model,
                the migration, the service, the handler, the routes, the Zod schema, the
                TypeScript types and an admin screen, and registers all of it.
              </p>
              <CodeBlock terminal language="bash" code={`grit generate resource Group \\
  --fields "name:string,description:text"`} />
              <p>
                Then the contact, with a photo and a group to belong to. The{' '}
                <code>belongs_to:Group</code> field is what makes the admin screen render a picker
                rather than a text box asking for an id.
              </p>
              <CodeBlock terminal language="bash" code={`grit generate resource Contact \\
  --fields "name:string,email:email,phone:tel,photo:file:image,group:belongs_to:Group"`} />

              <h2>3. Build the database</h2>
              <CodeBlock terminal language="bash" code={`grit migrate
grit seed`} />
              <p>
                <code>grit migrate</code> creates the tables from the models, and{' '}
                <code>grit seed</code> fills them: an administrator you can sign in as, a few
                users, and an API key. The administrator is{' '}
                <code>admin@example.com</code> with the password <code>admin123</code>. Change it
                before anybody else can reach the machine.
              </p>

              <h2>4. Run it</h2>
              <CodeBlock terminal language="bash" code={`grit start`} />
              <p>There are no frontends to start, so this runs the API alone, with hot reload.</p>

              <table className="w-full text-sm my-6">
                <thead>
                  <tr className="border-b border-border/50 text-left">
                    <th className="px-4 py-2.5 font-medium">Where</th>
                    <th className="px-4 py-2.5 font-medium">What</th>
                  </tr>
                </thead>
                <tbody>
                  <tr className="border-b border-border/30">
                    <td className="px-4 py-2.5 font-mono text-xs text-primary">http://localhost:8080/api/v1</td>
                    <td className="px-4 py-2.5 text-muted-foreground">The API</td>
                  </tr>
                  <tr className="border-b border-border/30">
                    <td className="px-4 py-2.5 font-mono text-xs text-primary">http://localhost:8080/docs</td>
                    <td className="px-4 py-2.5 text-muted-foreground">The reference, generated from the routes</td>
                  </tr>
                  <tr className="border-b border-border/30">
                    <td className="px-4 py-2.5 font-mono text-xs text-primary">http://localhost:8080/studio</td>
                    <td className="px-4 py-2.5 text-muted-foreground">GORM Studio: browse and edit the tables</td>
                  </tr>
                </tbody>
              </table>

              <h2>5. What you have</h2>
              <p>
                Two resources, and for each of them: a table with sorting, filtering, search,
                pagination, bulk edit and CSV import and export; a form that validates on both
                sides from one schema; and REST endpoints under <code>/api/v1/groups</code> and{' '}
                <code>/api/v1/contacts</code> with the same rules applied.
              </p>
              <p>
                The photo field is a real upload: the browser asks the API for a presigned URL and
                sends the file straight to storage, so the file never passes through the API
                process. With <code>STORAGE_DRIVER=local</code> that storage is a directory on
                disk, which is the default when there is no MinIO to talk to.
              </p>

              <h2>6. Deploy it</h2>
              <CodeBlock terminal language="bash" code={`grit deploy --host user@server.com --domain api.example.com

# Or a container, if that is your shape
docker compose -f docker-compose.prod.yml up --build`} />
              <p>The simplest tier to deploy, because there is one thing to deploy. The Docker form builds the API image and brings up Postgres and Redis beside it.</p>
              <p>
                Before any of that, read the{' '}
                <Link href="/docs/deployment/checklist">go-live checklist</Link>: it is the list of
                things that are fine in development and not in production, starting with the
                seeded password above and the secrets in <code>.env</code>.
              </p>
            </div>

            <div className="mt-16 flex flex-col sm:flex-row gap-4 justify-between border-t border-border pt-8">
              <Button variant="ghost" asChild>
                <Link href="/docs/tutorials/contacts/mobile">
                  <ArrowLeft className="mr-2 h-4 w-4" />
                  The mobile app
                </Link>
              </Button>
              <Button variant="ghost" asChild>
                <Link href="/docs/tutorials/contacts/single">
                  One binary
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Link>
              </Button>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
