package handlers

import (
	"net/http"

	"github.com/gin-gonic/gin"

	"commerce/apps/api/internal/files"
	"commerce/apps/api/internal/models"
	"commerce/apps/api/internal/paginate"
)

// The public collections surface.
//
// Generated by grit with --public. Two read endpoints, mounted outside auth and
// guarded by an API key, for clients with no logged-in user: a storefront, a
// mobile app, a public directory.
//
// Regenerating the resource does NOT overwrite this file, so the allowlist
// below is yours to edit.

// publicCollection is what an anonymous caller is allowed to see.
//
// An allowlist rather than the model. A column added next month is private
// until somebody adds it here, which is the correct default when the audience
// is the internet, and the opposite of the admin surface's default.
type publicCollection struct {
	ID          string         `json:"id"`
	Title       string         `json:"title"`
	Handle      string         `json:"handle"`
	Description string         `json:"description"`
	Image       *files.FileRef `json:"image"`
}

func toPublicCollection(m models.Collection) publicCollection {
	return publicCollection{
		ID:          m.ID,
		Title:       m.Title,
		Handle:      m.Handle,
		Description: m.Description,
		Image:       m.Image,
	}
}

// ListPublic handles GET /api/v1/public/collections.
//
// Supports ?search=, ?sort_by= and ?sort_order=, ?page= and ?page_size=,
// equality filters on the published columns, and a ?x_min= / ?x_max= window on
// the numeric ones.
func (h *CollectionHandler) ListPublic(c *gin.Context) {
	// The service decides what "live" means and it is not settable from here:
	// archived_at and the visibility column are deliberately absent from the
	// filter lists below, because a column listed there is settable from the
	// query string, and ?active=false would hand back rows somebody took down
	// on purpose.
	res, err := h.service().ListPublic(c.Request.Context(), paginate.Bind(c), paginate.Config{
		Searchable: []string{"title", "handle", "description"},
		Sortable:   map[string]bool{"title": true, "handle": true, "description": true, "created_at": true},
		// Published columns only, plus foreign keys. Anything not listed is
		// ignored rather than rejected, so an unknown query param is never an
		// error.
		Filterable:      map[string]bool{"title": true, "handle": true},
		RangeFilterable: map[string]bool{},
		// Foreign keys accept a comma-separated list, so one request can ask
		// for a whole category subtree.
		InFilterable: map[string]bool{},
	})
	if err != nil {
		h.fail(c, err, "Failed to fetch collections")
		return
	}

	out := make([]publicCollection, 0, len(res.Data))
	for _, m := range res.Data {
		out = append(out, toPublicCollection(m))
	}
	c.JSON(http.StatusOK, gin.H{"data": out, "meta": res.Meta})
}

// GetPublic handles GET /api/v1/public/collections/:key.
//
// Looks up by handle, so a public URL reads as something a person
// could type rather than a UUID.
func (h *CollectionHandler) GetPublic(c *gin.Context) {
	item, err := h.service().GetPublic(c.Request.Context(), c.Param("key"))
	if err != nil {
		h.fail(c, err, "Failed to load collection")
		return
	}
	c.JSON(http.StatusOK, gin.H{"data": toPublicCollection(*item)})
}
