package handlers

import (
	"net/http"
	"strconv"

	"github.com/gin-gonic/gin"

	"commerce/apps/api/internal/files"
	"commerce/apps/api/internal/models"
	"commerce/apps/api/internal/money"
	"commerce/apps/api/internal/paginate"
)

// The public products surface.
//
// Generated by grit with --public. Two read endpoints, mounted outside auth and
// guarded by an API key, for clients with no logged-in user: a storefront, a
// mobile app, a public directory.
//
// Regenerating the resource does NOT overwrite this file, so the allowlist
// below is yours to edit.

// publicProduct is what an anonymous caller is allowed to see.
//
// An allowlist rather than the model. A column added next month is private
// until somebody adds it here, which is the correct default when the audience
// is the internet, and the opposite of the admin surface's default.
type publicProduct struct {
	ID            string         `json:"id"`
	CollectionID  string         `json:"collection_id"`
	Title         string         `json:"title"`
	Handle        string         `json:"handle"`
	Description   string         `json:"description"`
	Price         money.Money    `json:"price"`
	FeaturedImage *files.FileRef `json:"featured_image"`
	Images        files.FileRefs `json:"images"`
	Available     bool           `json:"available"`
}

func toPublicProduct(m models.Product) publicProduct {
	return publicProduct{
		ID:            m.ID,
		CollectionID:  m.CollectionID,
		Title:         m.Title,
		Handle:        m.Handle,
		Description:   m.Description,
		Price:         m.Price,
		FeaturedImage: m.FeaturedImage,
		Images:        m.Images,
		Available:     m.Available,
	}
}

// ListPublic handles GET /api/v1/public/products.
//
// Supports ?search=, ?sort_by= and ?sort_order=, ?page= and ?page_size=,
// equality filters on the published columns, and a ?x_min= / ?x_max= window on
// the numeric ones.
func (h *ProductHandler) ListPublic(c *gin.Context) {
	// The service decides what "live" means and it is not settable from here:
	// archived_at and the visibility column are deliberately absent from the
	// filter lists below, because a column listed there is settable from the
	// query string, and ?active=false would hand back rows somebody took down
	// on purpose.
	res, err := h.service().ListPublic(c.Request.Context(), paginate.Bind(c), paginate.Config{
		Searchable: []string{"title", "handle"},
		Sortable:   map[string]bool{"title": true, "handle": true, "price_amount": true, "created_at": true},
		// Published columns only, plus foreign keys. Anything not listed is
		// ignored rather than rejected, so an unknown query param is never an
		// error.
		Filterable:      map[string]bool{"title": true, "handle": true, "available": true},
		RangeFilterable: map[string]bool{"price_amount": true},
		// Foreign keys accept a comma-separated list, so one request can ask
		// for a whole category subtree.
		InFilterable: map[string]bool{"collection_id": true},
	})
	if err != nil {
		h.fail(c, err, "Failed to fetch products")
		return
	}

	out := make([]publicProduct, 0, len(res.Data))
	for _, m := range res.Data {
		out = append(out, toPublicProduct(m))
	}
	c.JSON(http.StatusOK, gin.H{"data": out, "meta": res.Meta})
}

// GetPublic handles GET /api/v1/public/products/:key.
//
// Looks up by handle, so a public URL reads as something a person
// could type rather than a UUID.
func (h *ProductHandler) GetPublic(c *gin.Context) {
	item, err := h.service().GetPublic(c.Request.Context(), c.Param("key"))
	if err != nil {
		h.fail(c, err, "Failed to load product")
		return
	}
	c.JSON(http.StatusOK, gin.H{"data": toPublicProduct(*item)})
}

// RelatedPublic handles GET /api/v1/public/products/:key/related.
//
// The "similar items" strip on a detail page: others sharing this one's
// collection, newest first, this one excluded.
//
// Capped at 24 however large ?limit= asks, because this endpoint exists to
// fill a row of cards and an uncapped limit on a public route is a free way
// to make the database do work.
func (h *ProductHandler) RelatedPublic(c *gin.Context) {
	item, err := h.service().GetPublic(c.Request.Context(), c.Param("key"))
	if err != nil {
		h.fail(c, err, "Failed to load product")
		return
	}

	limit := 8
	if raw := c.Query("limit"); raw != "" {
		if n, convErr := strconv.Atoi(raw); convErr == nil && n > 0 {
			limit = n
		}
	}
	if limit > 24 {
		limit = 24
	}

	rows, err := h.service().RelatedPublic(c.Request.Context(), item, limit)
	if err != nil {
		h.fail(c, err, "Failed to fetch related products")
		return
	}

	out := make([]publicProduct, 0, len(rows))
	for _, m := range rows {
		out = append(out, toPublicProduct(m))
	}
	c.JSON(http.StatusOK, gin.H{"data": out})
}
