// Package access reports what each route demands of a caller.
//
// # Why this is a generated table and not a runtime lookup
//
// Gin's router can be asked for its table, and the answer carries a route's
// method, path and last handler. It carries nothing about the middleware in
// front of it: RouteInfo has no chain. So at runtime the process genuinely does
// not know that /api/v1/widgets is behind RequireRole("ADMIN",
// "perm:widgets.view"), and anything it reported would be a guess.
//
// A guess here is worse than silence. Guessed from the path, /api/v1/auth/me
// and all six passkey endpoints read as public, because they sit under /auth/,
// and every one of them needs a signed-in user. Somebody would read that column
// as a security statement.
//
// So the table is built where the truth is: `grit` parses routes.go and the
// per-resource route files, resolves each group's middleware chain, and writes
// registry.go. It is regenerated by `grit new`, `grit generate resource`,
// `grit remove` and `grit upgrade`, and `grit doctor` fails when it is stale.
//
// # Reading the result honestly
//
// Of returns ok=false for a route the table does not know, and that is a real
// answer, not an error. The reference at /docs, the profiler and the database
// browser mount their own routes and are not in routes.go, so nothing here can
// speak for them. A caller must render that case as unknown rather than as
// public: the whole point of this package is to never say public about a route
// it has not read.
package access

import "strings"

// Requirement is what a route demands of a caller.
type Requirement struct {
	// Group is the bucket the route is mounted in: public, protected, staff,
	// admin or api-key. It comes from the group's middleware chain alone.
	Group string `json:"group"`

	// Roles and Permissions are what the route demands. Either satisfies it:
	// RequireRole("ADMIN", "perm:widgets.view") admits an ADMIN or anybody
	// granted widgets.view.
	Roles       []string `json:"roles,omitempty"`
	Permissions []string `json:"permissions,omitempty"`

	// Authenticated is true when something in front of the route establishes
	// who is calling: a session, a bearer token or an API key.
	Authenticated bool `json:"authenticated"`

	// APIKeyOnly is true when an API key alone is accepted, with no user
	// session.
	APIKeyOnly bool `json:"api_key_only,omitempty"`

	// Staff is true when RequireStaff gates the route: it admits the ADMIN role
	// or anybody holding any permission at all, and the route behind it names
	// the permission it actually needs.
	Staff bool `json:"staff,omitempty"`

	// Summary is the requirement as one short phrase, for a column or a badge.
	Summary string `json:"summary"`
}

// Public reports whether the route can be called with no credentials at all.
//
// A method rather than a field so the question has one answer. A caller
// checking Summary == "public" would also match a route the table does not
// know, whose summary is empty.
func (r Requirement) Public() bool {
	return !r.Authenticated && len(r.Roles) == 0 && len(r.Permissions) == 0
}

// Of returns the requirement for a method and a route pattern as gin
// registered it, such as ("GET", "/api/v1/widgets/:id").
//
// ok is false for a route this table does not cover, which the caller must
// render as unknown. See the package comment.
func Of(method, path string) (Requirement, bool) {
	req, ok := table[strings.ToUpper(method)+" "+path]
	return req, ok
}

// Count is how many routes the table holds, which is how many routes the
// project's own route files register. It is smaller than the router's table,
// because mounted dashboards bring their own.
func Count() int {
	return len(table)
}

// All returns the whole table, keyed by "<METHOD> <path>".
//
// The copy is deliberate: the table is package state and a caller that ranged
// over it directly could delete from it.
func All() map[string]Requirement {
	out := make(map[string]Requirement, len(table))
	for key, req := range table {
		out[key] = req
	}
	return out
}
