// Package accessgen writes a project's access table from its route files.
//
// The table answers "what does this route demand of a caller", which the
// running process cannot work out for itself: gin's RouteInfo carries a route's
// last handler and nothing about the middleware in front of it. The truth lives
// in routes.go and the per-resource route files, so it is read there, once, and
// written as Go that the project compiles in.
//
// Regenerated by `grit new`, `grit generate resource`, `grit remove` and
// `grit upgrade`. `grit doctor` reports when it has gone stale, which is what
// happens when somebody adds a route by hand, and staleness is a reported
// warning rather than a silent wrong answer because the alternative is an
// access column that lies.
package accessgen

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/MUKE-coder/grit/v3/internal/routeparser"
)

// Header is the first line of the generated file, and the marker that tells
// Generate it may overwrite what is there.
const Header = "// Code generated by grit. DO NOT EDIT."

// Result reports what Generate did, so a caller can print one honest line.
type Result struct {
	// Path is the file written, relative to the project root.
	Path string
	// Routes is how many routes the table holds.
	Routes int
	// Changed is false when the file on disk already said this.
	Changed bool
}

// Generate writes <api>/internal/access/registry.go from the project's route
// files and reports what it found.
//
// A project with no routes.go is not an error: `grit new --api` in a directory
// that is not a Grit project, and the desktop and lite shapes, all reach here.
// Generate returns a zero Result and no error, because refusing to scaffold
// over a missing optional file is worse than skipping it.
func Generate(root string) (Result, error) {
	routesFile, err := routeparser.FindRoutesFile(root)
	if err != nil {
		return Result{}, nil
	}

	routes, err := routeparser.ParseProject(routesFile)
	if err != nil {
		return Result{}, fmt.Errorf("reading routes: %w", err)
	}

	dir := filepath.Join(filepath.Dir(filepath.Dir(routesFile)), "access")
	target := filepath.Join(dir, "registry.go")

	// A hand-written file in this place is left alone. It can only get there
	// deliberately, and overwriting somebody's code because it sits at a path
	// we wanted is the one thing the upgrade machinery exists not to do.
	if existing, err := os.ReadFile(target); err == nil {
		if !strings.HasPrefix(strings.TrimSpace(string(existing)), Header) {
			return Result{}, fmt.Errorf("%s is not generated by grit; delete it or move your code elsewhere", target)
		}
		if string(existing) == render(routes) {
			return Result{Path: rel(root, target), Routes: len(routes)}, nil
		}
	}

	if err := os.MkdirAll(dir, 0o755); err != nil {
		return Result{}, fmt.Errorf("creating %s: %w", dir, err)
	}
	if err := os.WriteFile(target, []byte(render(routes)), 0o644); err != nil {
		return Result{}, fmt.Errorf("writing %s: %w", target, err)
	}

	return Result{Path: rel(root, target), Routes: len(routes), Changed: true}, nil
}

// Stale reports whether the generated table still matches the route files.
//
// Used by `grit doctor`. It returns false with no error for a project that has
// no table yet, because a project from before this existed is not broken, it
// just has not been upgraded.
func Stale(root string) (bool, error) {
	routesFile, err := routeparser.FindRoutesFile(root)
	if err != nil {
		return false, nil
	}
	target := filepath.Join(filepath.Dir(filepath.Dir(routesFile)), "access", "registry.go")

	existing, err := os.ReadFile(target)
	if err != nil {
		return false, nil
	}
	if !strings.HasPrefix(strings.TrimSpace(string(existing)), Header) {
		return false, nil
	}

	routes, err := routeparser.ParseProject(routesFile)
	if err != nil {
		return false, fmt.Errorf("reading routes: %w", err)
	}
	return string(existing) != render(routes), nil
}

// render builds the generated file, gofmt'd.
//
// Written as a sorted list rather than a map literal in source order so the
// output is byte-identical for the same input, which is what lets Generate
// skip the write and lets Stale compare by content.
//
// The gofmt pass is not cosmetic. A generated project runs `gofmt -l` in its
// own CI, and a file this tool wrote failing that check is a build somebody
// else has to debug. If formatting fails the unformatted source is returned
// rather than nothing: it still compiles, and a missing access table is worse
// than an ugly one.
func render(routes []routeparser.Route) string {
	src := renderRaw(routes)
	pretty, err := format.Source([]byte(src))
	if err != nil {
		return src
	}
	return string(pretty)
}

func renderRaw(routes []routeparser.Route) string {
	type entry struct {
		key   string
		route routeparser.Route
	}

	// Two routes can share a method and path only if routes.go registers the
	// same one twice, which gin itself panics on. Keeping the first is
	// therefore unreachable in a project that starts, and defined behaviour in
	// one that does not.
	seen := map[string]bool{}
	var entries []entry
	for _, r := range routes {
		key := r.Method + " " + r.Path
		if seen[key] {
			continue
		}
		seen[key] = true
		entries = append(entries, entry{key: key, route: r})
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].key < entries[j].key })

	var b strings.Builder
	b.WriteString(Header + "\n")
	b.WriteString("//\n")
	b.WriteString("// Built from routes.go and the per-resource route files by `grit`. See the\n")
	b.WriteString("// access package comment for why this is generated rather than read at runtime.\n")
	b.WriteString("\npackage access\n\n")
	fmt.Fprintf(&b, "// table holds every route the project's own route files register (%d).\n", len(entries))
	b.WriteString("var table = map[string]Requirement{\n")

	for _, e := range entries {
		a := e.route.Access
		fmt.Fprintf(&b, "\t%s: {\n", strconv.Quote(e.key))
		fmt.Fprintf(&b, "\t\tGroup: %s,\n", strconv.Quote(e.route.Group))
		if len(a.Roles) > 0 {
			fmt.Fprintf(&b, "\t\tRoles: %s,\n", goStrings(a.Roles))
		}
		if len(a.Permissions) > 0 {
			fmt.Fprintf(&b, "\t\tPermissions: %s,\n", goStrings(a.Permissions))
		}
		if a.Authenticated {
			b.WriteString("\t\tAuthenticated: true,\n")
		}
		if a.APIKeyOnly {
			b.WriteString("\t\tAPIKeyOnly: true,\n")
		}
		if a.Staff {
			b.WriteString("\t\tStaff: true,\n")
		}
		fmt.Fprintf(&b, "\t\tSummary: %s,\n", strconv.Quote(a.Summary()))
		b.WriteString("\t},\n")
	}

	b.WriteString("}\n")
	return b.String()
}

func goStrings(values []string) string {
	quoted := make([]string, len(values))
	for i, v := range values {
		quoted[i] = strconv.Quote(v)
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}

func rel(root, path string) string {
	if out, err := filepath.Rel(root, path); err == nil {
		return filepath.ToSlash(out)
	}
	return path
}
