import { CodeBlock } from '@/components/code-block'
import { TipBox } from '@/components/course/tip-box'
import { Exercise } from '@/components/course/exercise'
import { KnowledgeCheck } from '@/components/course/knowledge-check'
import { Diagram } from '@/components/course/diagram'

export default function Lesson() {
  return (
    <>
      <p>
        With four frontends, type drift is the silent killer. Web
        thinks <code>price</code> is a number; mobile thinks it&apos;s a
        string; desktop forgot to update after the API renamed it.
        Cue the production bug. <code>grit sync</code> exists to
        kill that whole category.
      </p>

      <h2>One Go model, four frontends</h2>
      <Diagram label="grit sync flow" caption="One command updates the type for every frontend at once.">
{`   apps/api/internal/models/product.go
            │
            │  grit sync
            ▼
   packages/shared/types/product.ts
            │
   ┌────────┼────────┬────────┐
   │        │        │        │
   ▼        ▼        ▼        ▼
  web    admin   mobile   desktop`}
      </Diagram>

      <h2>The Go model is the source of truth</h2>
      <CodeBlock
        language="go"
        filename="apps/api/internal/models/product.go"
        code={`package models

import "time"

type Product struct {
  ID         uint      \`gorm:"primaryKey" json:"id"\`
  Name       string    \`gorm:"not null"   json:"name"\`
  Slug       string    \`gorm:"uniqueIndex" json:"slug"\`
  PriceCents int       \`gorm:"not null"   json:"price_cents"\`
  Currency   string    \`gorm:"default:USD" json:"currency"\`
  InStock    bool      \`json:"in_stock"\`
  Tags       string    \`gorm:"type:text" json:"tags"\`  // CSV
  CreatedAt  time.Time \`json:"created_at"\`
  UpdatedAt  time.Time \`json:"updated_at"\`
}`}
      />

      <h2>Run grit sync</h2>
      <CodeBlock
        language="bash"
        code={`grit sync
# scans apps/api/internal/models/*.go
# writes packages/shared/types/*.ts
# writes packages/shared/zod/*.ts`}
      />

      <h2>What gets generated</h2>
      <CodeBlock
        language="ts"
        filename="packages/shared/types/product.ts (generated — do not edit)"
        code={`// Generated by grit sync. Do not edit.
export interface Product {
  id: number
  name: string
  slug: string
  price_cents: number
  currency: string
  in_stock: boolean
  tags: string
  created_at: string
  updated_at: string
}

export interface CreateProductInput {
  name: string
  slug: string
  price_cents: number
  currency?: string
  in_stock?: boolean
  tags?: string
}`}
      />
      <p>
        Notice: <code>CreateProductInput</code> drops the
        server-managed fields (ID, timestamps) and makes
        defaulted-fields optional. That&apos;s what you POST to
        <code> /api/products</code>.
      </p>

      <h2>The naming rule — snake vs. camel</h2>
      <p>
        Go convention is <code>PriceCents</code>; JSON convention is{' '}
        <code>price_cents</code>. The TS file mirrors the JSON tag, NOT
        the Go field name, because that&apos;s what comes off the wire.
      </p>
      <p>
        If you prefer camelCase on the frontend, change the JSON tag
        in Go: <code>json:&quot;priceCents&quot;</code>. The frontend
        type will update next sync. Pick one and stay consistent.
      </p>

      <TipBox tone="warning">
        <strong>Don&apos;t hand-edit the generated files.</strong> A
        big comment at the top says so, but it&apos;s tempting on a
        Friday afternoon. Your edit will be wiped on the next sync.
        If you need a frontend-only field (e.g., a computed display
        value), put it in a separate type that <em>extends</em> the
        generated one.
      </TipBox>

      <h2>Add the field once — all frontends gain it</h2>
      <p>
        Suppose marketing asks for a Featured badge. Steps:
      </p>
      <ol>
        <li>Add <code>IsFeatured bool</code> to the Go struct.</li>
        <li><code>grit sync</code>.</li>
        <li>Web, admin, mobile, desktop — all four IDEs now show the field.</li>
        <li>Run a DB migration (grit generates one too) so the column exists.</li>
      </ol>
      <p>
        Five seconds of typing, zero copies, zero drift.
      </p>

      <h2>What sync does NOT do</h2>
      <ul>
        <li>
          <strong>Doesn&apos;t generate API client code.</strong> The
          shared package gives you the <em>types</em>; each surface
          still calls <code>fetch</code> (web/admin/desktop) or the
          mobile API wrapper. Types make the calls safe, not
          automatic.
        </li>
        <li>
          <strong>Doesn&apos;t touch your existing UI.</strong> Add a
          field, the type changes; whether the UI shows it is on you.
          TS will flag where you destructure the type but ignore the
          new field as a soft warning if you enable it.
        </li>
        <li>
          <strong>Doesn&apos;t roll back a deleted Go field.</strong>{' '}
          Remove a field in Go, sync, and the TS shape becomes
          narrower. Any code referencing the old field now type-errors
          — which is the point.
        </li>
      </ul>

      <KnowledgeCheck
        question="You add nickname to the Go User model and run grit sync. The web app immediately type-errors because UserCard.tsx tries to read user.nicname (typo). Why is this a good thing?"
        choices={[
          {
            label: 'It catches the typo at compile time, not at runtime when a real user tries it',
            correct: true,
            feedback:
              'Right — the type error fails the build with a clear message. Without shared types, you’d ship the typo and notice when the field shows up as undefined in the UI.',
          },
          {
            label: 'It forces you to update every frontend before merging',
            feedback:
              'Sort of — but the value isn’t the discipline, it’s the early signal. You can pick when to merge.',
          },
          {
            label: 'It makes the build slow',
            feedback:
              'Type-checking is fast. The slowness is in your perception when the build fails — but a failed build is way cheaper than a prod bug.',
          },
          {
            label: 'It prevents you from shipping until the API is also updated',
            feedback:
              'Backwards — the API change drove the type change. The error is on the frontend, not the API.',
          },
        ]}
      />

      <Exercise
        prompt={
          <>
            <p>Feel the four-surface wave:</p>
            <ol>
              <li>
                Add <code>IsFeatured bool `gorm:&quot;default:false&quot; json:&quot;is_featured&quot;`</code> to the Product Go model.
              </li>
              <li>Run <code>grit sync</code> from the repo root.</li>
              <li>
                Open the generated <code>packages/shared/types/product.ts</code>{' '}
                — confirm <code>is_featured</code> is there.
              </li>
              <li>
                Run <code>pnpm type-check</code> at the root. Should
                pass (we&apos;re adding a field, not breaking existing
                code).
              </li>
              <li>
                Use <code>product.is_featured</code> in ONE component in
                each of web, admin, mobile, desktop — even just rendering
                &quot;★&quot; if true. Confirm autocomplete in all four IDEs.
              </li>
            </ol>
          </>
        }
        hint={
          <>
            If you don&apos;t see is_featured in mobile&apos;s
            autocomplete, restart Metro (Expo uses a separate TS
            server). Cmd/Ctrl+R inside the running terminal usually
            fixes it.
          </>
        }
        solution={
          <>
            <p>
              You should see the new field show up everywhere. The cost
              of supporting four frontends collapses from &quot;four
              edits&quot; to &quot;one&quot;.
            </p>
            <p>
              That&apos;s the unique value of Grit on a multi-surface
              product — type sync is the difference between &quot;we
              ship to mobile too&quot; being a roadmap item or a
              shrug.
            </p>
          </>
        }
      />

      <h2>What&apos;s next</h2>
      <p>
        Next lesson — <strong>Shared Zod schemas</strong>. Types tell
        you what shape data has; Zod validates that the runtime data
        actually matches that shape. Both sides of the input boundary.
      </p>
    </>
  )
}
