// GENERATED by scripts/generate-block-map.mjs — do not edit by hand.
// Run `pnpm gen` after adding or removing a block in registry/.

import dynamic from 'next/dynamic'
import type { ComponentType } from 'react'

/** Keyed by the flat registry name: <category>-<subcategory>-<slug>. */
export const BLOCK_MAP: Record<string, ComponentType> = {
  "marketing-hero-sections-simple-centered": dynamic(() => import('@/registry/marketing/hero-sections/simple-centered').then((m) => ({ default: m.default }))),
  "marketing-hero-sections-split-with-code": dynamic(() => import('@/registry/marketing/hero-sections/split-with-code').then((m) => ({ default: m.default }))),
  "marketing-hero-sections-with-app-screenshot": dynamic(() => import('@/registry/marketing/hero-sections/with-app-screenshot').then((m) => ({ default: m.default }))),
}

/** 3 blocks at generation time. */
export const BLOCK_COUNT: number = 3
