package scaffold

import "strings"

// APIVariantServiceTestGo emits the tests that ship with a variant install.
//
// Price resolution is the thing worth testing, because every failure mode is
// silent: a wrong price does not crash, it renders, and the customer pays it.
func APIVariantServiceTestGo(module, pascal, snake string) string {
	return perResource(apiVariantServiceTestGo(module, pascal, snake), pascal, "buildShirt", "loadOptionsByID", "variantTestDB")
}

func apiVariantServiceTestGo(module, pascal, snake string) string {
	lower := strings.ToLower(pascal)
	return `package services_test

import (
	"testing"

	"github.com/glebarez/sqlite"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"

	"` + module + `/internal/models"
	"` + module + `/internal/services"
)

// Generated by grit add variants.
//
// Price resolution is what these are for. Every way it can go wrong is silent:
// a wrong price does not throw, it renders, and somebody pays it.

func variantTestDB(t *testing.T) *gorm.DB {
	t.Helper()
	db, err := gorm.Open(sqlite.Open(":memory:"), &gorm.Config{
		Logger: logger.Default.LogMode(logger.Silent),
	})
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	// SQLite does not enforce foreign keys unless asked, and Postgres always
	// does. Without this a join table can point at a row that is not there and
	// the tests still pass.
	db.Exec("PRAGMA foreign_keys = ON")
	err = db.AutoMigrate(
		&models.` + pascal + `{}, &models.Option{}, &models.OptionValue{},
		&models.` + pascal + `Option{}, &models.` + pascal + `OptionValue{}, &models.` + pascal + `Variant{},
	)
	if err != nil {
		t.Fatalf("migrate: %v", err)
	}
	return db
}

// buildShirt sets up the case every shop has: one axis that changes the price
// and one that does not.
func buildShirt(t *testing.T, db *gorm.DB) (` + snake + `ID string, colours, sizes models.Option) {
	t.Helper()

	// Enforcement is off for this one insert, and on for everything after it.
	//
	// The resource under test may have required parents of its own — a
	// category, an owner, a tenant — that have nothing to do with variants.
	// Satisfying those would mean this generated file knowing the shape of a
	// model it did not generate, and getting it wrong would fail the suite for
	// a reason that is not about pricing. What these tests are actually about,
	// the option and variant graph, is written with the constraints on.
	db.Exec("PRAGMA foreign_keys = OFF")
	` + snake + ` := models.` + pascal + `{Name: "Cotton shirt", Price: 40}
	createErr := db.Create(&` + snake + `).Error
	db.Exec("PRAGMA foreign_keys = ON")
	if createErr != nil {
		t.Fatalf("create ` + lower + `: %v", createErr)
	}

	colours = models.Option{Name: "Colour", Kind: "swatch", AffectsPrice: false, Position: 0}
	sizes = models.Option{Name: "Size", Kind: "size", AffectsPrice: true, Position: 1}
	db.Create(&colours)
	db.Create(&sizes)

	db.Create(&models.OptionValue{OptionID: colours.ID, Label: "Red", Swatch: "#c00", PriceDelta: 0})
	db.Create(&models.OptionValue{OptionID: colours.ID, Label: "Blue", Swatch: "#00c", PriceDelta: 0})
	db.Create(&models.OptionValue{OptionID: sizes.ID, Label: "M", PriceDelta: 0})
	db.Create(&models.OptionValue{OptionID: sizes.ID, Label: "XXL", PriceDelta: 5})

	db.Create(&models.` + pascal + `Option{` + pascal + `ID: ` + snake + `.ID, OptionID: colours.ID, Position: 0})
	db.Create(&models.` + pascal + `Option{` + pascal + `ID: ` + snake + `.ID, OptionID: sizes.ID, Position: 1})

	return ` + snake + `.ID, colours, sizes
}

func loadOptionsByID(t *testing.T, db *gorm.DB) map[string]models.Option {
	t.Helper()
	var options []models.Option
	db.Find(&options)
	byID := make(map[string]models.Option, len(options))
	for _, option := range options {
		byID[option.ID] = option
	}
	return byID
}

func Test` + pascal + `VariantPriceUsesOnlyPriceAffectingOptions(t *testing.T) {
	db := variantTestDB(t)
	svc := services.New` + pascal + `VariantService(db)
	id, _, _ := buildShirt(t, db)

	if _, err := svc.Generate(id, 100); err != nil {
		t.Fatalf("Generate: %v", err)
	}
	byID := loadOptionsByID(t, db)

	variants, err := svc.VariantsFor(id)
	if err != nil {
		t.Fatalf("VariantsFor: %v", err)
	}
	if len(variants) != 4 {
		t.Fatalf("2 colours x 2 sizes should be 4 variants, got %d", len(variants))
	}

	for _, variant := range variants {
		price := svc.ResolvePrice(40, variant, byID)
		isXXL := false
		for _, value := range variant.OptionValues {
			if value.Label == "XXL" {
				isXXL = true
			}
		}
		want := 40.0
		if isXXL {
			want = 45.0
		}
		if price != want {
			labels := []string{}
			for _, v := range variant.OptionValues {
				labels = append(labels, v.Label)
			}
			t.Errorf("%v priced at %.2f, want %.2f. Colour must not move the price and size must",
				labels, price, want)
		}
	}
}

func Test` + pascal + `VariantOverrideWins(t *testing.T) {
	db := variantTestDB(t)
	svc := services.New` + pascal + `VariantService(db)
	id, _, _ := buildShirt(t, db)
	svc.Generate(id, 100)
	byID := loadOptionsByID(t, db)

	variants, _ := svc.VariantsFor(id)
	override := 12.34
	variants[0].PriceOverride = &override

	if got := svc.ResolvePrice(40, variants[0], byID); got != 12.34 {
		t.Errorf("an override must win outright, got %.2f", got)
	}
}

// The reason the price is computed rather than stored: a base price change has
// to reach every variant that has no override, immediately.
func Test` + pascal + `VariantPriceFollowsTheBasePrice(t *testing.T) {
	db := variantTestDB(t)
	svc := services.New` + pascal + `VariantService(db)
	id, _, _ := buildShirt(t, db)
	svc.Generate(id, 100)
	byID := loadOptionsByID(t, db)

	variants, _ := svc.VariantsFor(id)
	before := svc.ResolvePrice(40, variants[0], byID)
	after := svc.ResolvePrice(50, variants[0], byID)

	if after-before != 10 {
		t.Errorf("a base price rise of 10 moved the variant by %.2f", after-before)
	}
}

func Test` + pascal + `VariantFindByValuesMatchesExactly(t *testing.T) {
	db := variantTestDB(t)
	svc := services.New` + pascal + `VariantService(db)
	id, _, _ := buildShirt(t, db)
	svc.Generate(id, 100)

	variants, _ := svc.VariantsFor(id)
	target := variants[2]
	ids := []string{}
	for _, value := range target.OptionValues {
		ids = append(ids, value.ID)
	}

	found, err := svc.FindByValues(id, ids)
	if err != nil {
		t.Fatalf("FindByValues: %v", err)
	}
	if found.ID != target.ID {
		t.Errorf("found %s, want %s", found.ID, target.ID)
	}

	// One value alone must not match a two-axis variant. Comparing only the
	// asked-for ids would return the first variant that happens to include it.
	if _, err := svc.FindByValues(id, ids[:1]); err == nil {
		t.Error("a partial selection must not resolve to a variant")
	}
}

func Test` + pascal + `VariantGenerateIsIdempotentAndCapped(t *testing.T) {
	db := variantTestDB(t)
	svc := services.New` + pascal + `VariantService(db)
	id, _, _ := buildShirt(t, db)

	first, err := svc.Generate(id, 100)
	if err != nil || first != 4 {
		t.Fatalf("first run created %d (err %v), want 4", first, err)
	}

	// Somebody's work on the existing rows must survive a second run.
	variants, _ := svc.VariantsFor(id)
	db.Model(&variants[0]).Update("sku", "SHIRT-RED-M")

	second, err := svc.Generate(id, 100)
	if err != nil {
		t.Fatalf("second Generate: %v", err)
	}
	if second != 0 {
		t.Errorf("re-running created %d more variants, want 0", second)
	}

	var check models.` + pascal + `Variant
	db.Where("id = ?", variants[0].ID).First(&check)
	if check.SKU != "SHIRT-RED-M" {
		t.Error("regenerating overwrote an existing variant's sku")
	}

	if _, err := svc.Generate(id, 2); err == nil {
		t.Error("a limit below the combination count must refuse rather than write")
	}
}

// "From 49" has to be a price somebody can actually pay.
func Test` + pascal + `VariantPriceRangeSkipsOutOfStock(t *testing.T) {
	db := variantTestDB(t)
	svc := services.New` + pascal + `VariantService(db)
	id, _, _ := buildShirt(t, db)
	svc.Generate(id, 100)
	byID := loadOptionsByID(t, db)

	variants, _ := svc.VariantsFor(id)
	for _, variant := range variants {
		inStock := 0
		for _, value := range variant.OptionValues {
			if value.Label == "XXL" {
				inStock = 3
			}
		}
		db.Model(&models.` + pascal + `Variant{}).Where("id = ?", variant.ID).Update("stock", inStock)
	}

	variants, _ = svc.VariantsFor(id)
	low, high := svc.PriceRange(40, variants, byID)
	if low != 45 || high != 45 {
		t.Errorf("only the XXL variants are in stock, so the range is 45 to 45, got %.2f to %.2f", low, high)
	}
}

// A shop-wide axis, offered in different values by different ` + lower + `s.
//
// This is the case the option library could not express: offering Colour
// offered every colour in the shop, so a shirt in red only and a tee in red and
// blue had to be given two separate Colour options, and a filter could then
// never match across them. Found building a storefront on Grit.
func Test` + pascal + `OffersOnlySomeValuesOfAnAxis(t *testing.T) {
	db := ` + snake + `VariantTestDB(t)
	svc := services.New` + pascal + `VariantService(db)
	id, colours, _ := buildShirt(t, db)

	var red models.OptionValue
	if err := db.Where("option_id = ? AND label = ?", colours.ID, "Red").First(&red).Error; err != nil {
		t.Fatal(err)
	}

	if err := svc.SetOfferedValues(id, []string{red.ID}); err != nil {
		t.Fatal(err)
	}

	options, err := svc.OptionsFor(id)
	if err != nil {
		t.Fatal(err)
	}
	for _, option := range options {
		if option.ID != colours.ID {
			// The axis nobody narrowed keeps every value it has.
			if len(option.Values) != 2 {
				t.Errorf("%s offers %d values, want both: narrowing one axis narrowed another", option.Name, len(option.Values))
			}
			continue
		}
		if len(option.Values) != 1 || option.Values[0].Label != "Red" {
			labels := []string{}
			for _, value := range option.Values {
				labels = append(labels, value.Label)
			}
			t.Errorf("Colour offers %v, want only Red", labels)
		}
	}

	// And the matrix follows: two rows, not four.
	created, err := svc.Generate(id, 100)
	if err != nil {
		t.Fatal(err)
	}
	if created != 2 {
		t.Errorf("generated %d combinations, want 2: Red/M and Red/XXL", created)
	}
}

// Ticking every value of an axis is the same as not narrowing it, and has to
// be stored that way: a colour added to the shop next month must appear on a
// ` + lower + ` that offers the whole axis, not be silently left out of it.
func Test` + pascal + `OfferingEveryValueStoresNoNarrowing(t *testing.T) {
	db := ` + snake + `VariantTestDB(t)
	svc := services.New` + pascal + `VariantService(db)
	id, colours, _ := buildShirt(t, db)

	var values []models.OptionValue
	if err := db.Where("option_id = ?", colours.ID).Find(&values).Error; err != nil {
		t.Fatal(err)
	}
	all := []string{}
	for _, value := range values {
		all = append(all, value.ID)
	}

	if err := svc.SetOfferedValues(id, all); err != nil {
		t.Fatal(err)
	}
	stored, err := svc.OfferedValueIDs(id)
	if err != nil {
		t.Fatal(err)
	}
	if len(stored) != 0 {
		t.Errorf("stored %d rows for an axis offered whole, want none", len(stored))
	}

	// A value added later is therefore offered too.
	db.Create(&models.OptionValue{OptionID: colours.ID, Label: "Green", Swatch: "#0c0"})
	options, err := svc.OptionsFor(id)
	if err != nil {
		t.Fatal(err)
	}
	for _, option := range options {
		if option.ID == colours.ID && len(option.Values) != 3 {
			t.Errorf("Colour offers %d values, want 3: a value added to the shop was left out", len(option.Values))
		}
	}
}

// Narrowing to nothing is not a way to offer nothing: clearing the list puts
// the whole axis back, which is the only reading that lets somebody undo it.
func Test` + pascal + `ClearingTheNarrowingOffersTheWholeAxis(t *testing.T) {
	db := ` + snake + `VariantTestDB(t)
	svc := services.New` + pascal + `VariantService(db)
	id, colours, _ := buildShirt(t, db)

	var red models.OptionValue
	if err := db.Where("option_id = ? AND label = ?", colours.ID, "Red").First(&red).Error; err != nil {
		t.Fatal(err)
	}
	if err := svc.SetOfferedValues(id, []string{red.ID}); err != nil {
		t.Fatal(err)
	}
	if err := svc.SetOfferedValues(id, nil); err != nil {
		t.Fatal(err)
	}

	options, err := svc.OptionsFor(id)
	if err != nil {
		t.Fatal(err)
	}
	for _, option := range options {
		if len(option.Values) != 2 {
			t.Errorf("%s offers %d values after clearing the narrowing, want 2", option.Name, len(option.Values))
		}
	}
}

// A value of an axis this ` + lower + ` does not offer is not stored: the
// picker sends what it has, and an axis removed in the same edit would
// otherwise leave a row pointing at nothing.
func Test` + pascal + `IgnoresValuesOfAnAxisItDoesNotOffer(t *testing.T) {
	db := ` + snake + `VariantTestDB(t)
	svc := services.New` + pascal + `VariantService(db)
	id, colours, _ := buildShirt(t, db)

	// An option the ` + lower + ` does not offer at all.
	memory := models.Option{Name: "Memory", Kind: "select", AffectsPrice: true}
	db.Create(&memory)
	sixteen := models.OptionValue{OptionID: memory.ID, Label: "16GB"}
	db.Create(&sixteen)

	var red models.OptionValue
	if err := db.Where("option_id = ? AND label = ?", colours.ID, "Red").First(&red).Error; err != nil {
		t.Fatal(err)
	}

	if err := svc.SetOfferedValues(id, []string{red.ID, sixteen.ID}); err != nil {
		t.Fatal(err)
	}
	stored, err := svc.OfferedValueIDs(id)
	if err != nil {
		t.Fatal(err)
	}
	if len(stored) != 1 || stored[0] != red.ID {
		t.Errorf("stored %v, want only the value of an axis it offers", stored)
	}
}
`
}
