package scaffold

import (
	"fmt"
	"path/filepath"
)

func writeDesktopFrontendAppFiles(root string, opts DesktopOptions) error {
	files := map[string]string{
		filepath.Join(root, "frontend", "src", "App.tsx"):              desktopAppTSX(),
		filepath.Join(root, "frontend", "src", "lib", "utils.ts"):     desktopUtilsTS(),
		filepath.Join(root, "frontend", "src", "lib", "query-client.ts"): desktopQueryClientTS(),
		filepath.Join(root, "frontend", "src", "hooks", "use-auth.ts"):   desktopUseAuthHook(),
		filepath.Join(root, "frontend", "src", "hooks", "use-theme.ts"):  desktopUseThemeHook(),
	}

	for path, content := range files {
		if err := writeFile(path, content); err != nil {
			return fmt.Errorf("writing %s: %w", path, err)
		}
	}

	return nil
}

func desktopAppTSX() string {
	return `import { HashRouter, Routes, Route } from "react-router-dom";
import { Toaster } from "sonner";
import { AuthProvider } from "./hooks/use-auth";
import AppLayout from "./components/layout/app-layout";
import LoginPage from "./pages/login";
import RegisterPage from "./pages/register";
import DashboardPage from "./pages/dashboard";
import BlogListPage from "./pages/blogs/index";
import BlogFormPage from "./pages/blogs/form";
import ContactListPage from "./pages/contacts/index";
import ContactFormPage from "./pages/contacts/form";
// grit:page-imports

export default function App() {
  return (
    <AuthProvider>
      <HashRouter>
        <Routes>
          <Route path="/login" element={<LoginPage />} />
          <Route path="/register" element={<RegisterPage />} />
          <Route element={<AppLayout />}>
            <Route path="/" element={<DashboardPage />} />
            <Route path="/blogs" element={<BlogListPage />} />
            <Route path="/blogs/new" element={<BlogFormPage />} />
            <Route path="/blogs/:id/edit" element={<BlogFormPage />} />
            <Route path="/contacts" element={<ContactListPage />} />
            <Route path="/contacts/new" element={<ContactFormPage />} />
            <Route path="/contacts/:id/edit" element={<ContactFormPage />} />
            {/* grit:routes */}
          </Route>
        </Routes>
      </HashRouter>
      <Toaster
        theme="dark"
        position="bottom-right"
        toastOptions={{
          style: {
            background: "var(--bg-elevated)",
            border: "1px solid var(--border)",
            color: "var(--foreground)",
          },
        }}
      />
    </AuthProvider>
  );
}
`
}

func desktopUtilsTS() string {
	return `import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function formatDate(date: string | Date): string {
  return new Date(date).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}
`
}

func desktopQueryClientTS() string {
	return `import { QueryClient } from "@tanstack/react-query";

export const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 5 * 60 * 1000,
      retry: 1,
      refetchOnWindowFocus: false,
    },
    mutations: {
      retry: 0,
    },
  },
});
`
}

func desktopUseAuthHook() string {
	return `import { createContext, useContext, useState, useEffect, ReactNode } from "react";

// These are auto-generated by Wails — they will exist when wails dev runs
// @ts-ignore
import { Login as WailsLogin, Register as WailsRegister, GetCurrentUser } from "../../wailsjs/go/main/App";

interface User {
  id: number;
  name: string;
  email: string;
  role: string;
  created_at: string;
  updated_at: string;
}

interface AuthContextType {
  user: User | null;
  isAuthenticated: boolean;
  isLoading: boolean;
  login: (email: string, password: string) => Promise<void>;
  register: (name: string, email: string, password: string) => Promise<void>;
  logout: () => void;
}

const AuthContext = createContext<AuthContextType | null>(null);

export function AuthProvider({ children }: { children: ReactNode }) {
  const [user, setUser] = useState<User | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const stored = localStorage.getItem("grit-user");
    if (stored) {
      try {
        const parsed = JSON.parse(stored);
        if (parsed && parsed.id) {
          GetCurrentUser(parsed.id)
            .then((u: any) => {
              if (u) setUser(u);
              else localStorage.removeItem("grit-user");
            })
            .catch(() => localStorage.removeItem("grit-user"))
            .finally(() => setIsLoading(false));
          return;
        }
      } catch {
        // Invalid JSON in localStorage, ignore
      }
    }
    setIsLoading(false);
  }, []);

  const login = async (email: string, password: string) => {
    const response = await WailsLogin(email, password);
    setUser(response.user);
    localStorage.setItem("grit-user", JSON.stringify(response.user));
  };

  const register = async (name: string, email: string, password: string) => {
    const response = await WailsRegister(name, email, password);
    setUser(response.user);
    localStorage.setItem("grit-user", JSON.stringify(response.user));
  };

  const logout = () => {
    setUser(null);
    localStorage.removeItem("grit-user");
  };

  return (
    <AuthContext.Provider value={{ user, isAuthenticated: !!user, isLoading, login, register, logout }}>
      {children}
    </AuthContext.Provider>
  );
}

export function useAuth() {
  const context = useContext(AuthContext);
  if (!context) throw new Error("useAuth must be used within AuthProvider");
  return context;
}
`
}

func desktopUseThemeHook() string {
	return `import { useState, useEffect } from "react";

export function useTheme() {
  const [theme, setTheme] = useState<"dark" | "light">(() => {
    if (typeof window !== "undefined") {
      return (localStorage.getItem("grit-theme") as "dark" | "light") || "dark";
    }
    return "dark";
  });

  useEffect(() => {
    const root = document.documentElement;
    if (theme === "light") {
      root.classList.add("light");
      root.classList.remove("dark");
    } else {
      root.classList.add("dark");
      root.classList.remove("light");
    }
    localStorage.setItem("grit-theme", theme);
  }, [theme]);

  const toggleTheme = () => setTheme((t) => (t === "dark" ? "light" : "dark"));

  return { theme, setTheme, toggleTheme };
}
`
}
