package scaffold

import (
	"fmt"
	"path/filepath"
	"strings"
)

// writeDesktopInstallerFiles drops the Windows NSIS installer templates,
// the WebView2 staging directory, and the release-desktop.sh pipeline
// into the desktop scaffold. Two installers ship by default:
//
//   - project.nsi          — full installer (~150 MB) that bundles the
//                            Microsoft Edge WebView2 Evergreen Standalone
//                            Installer so it works on machines with no
//                            internet / no admin during first launch.
//   - project-slim.nsi     — slim installer (~22 MB) using the online
//                            Evergreen bootstrapper.
//
// The release pipeline (scripts/release-desktop.sh) builds the binary
// once and runs makensis twice with different -D flags to produce both.
func writeDesktopInstallerFiles(root string, opts DesktopOptions) error {
	files := map[string]string{
		filepath.Join(root, "build", "windows", "installer", "project.nsi"):         desktopNSIFull(opts),
		filepath.Join(root, "build", "windows", "installer", "project-slim.nsi"):    desktopNSISlim(opts),
		filepath.Join(root, "build", "windows", "installer", ".gitignore"):          desktopInstallerGitignore(),
		filepath.Join(root, "build", "windows", "installer", "README.md"):           desktopInstallerReadme(opts),
		filepath.Join(root, "build", "windows", "installer", "webview2", ".gitkeep"): "",
		filepath.Join(root, "scripts", "release-desktop.sh"):                        desktopReleaseScript(opts),
	}

	for path, content := range files {
		if err := writeFile(path, content); err != nil {
			return fmt.Errorf("writing %s: %w", path, err)
		}
	}
	return nil
}

/* ─── NSIS: full installer ────────────────────────────────────────── */

func desktopNSIFull(opts DesktopOptions) string {
	tpl := `####
## <PROJECT> NSIS installer — full variant
##
## Flow:
##   1. Welcome page — title + version + "Next"
##   2. Directory page — operator sees + can override the install path
##   3. Install page — file-extraction progress
##   4. Finish page — "Launch <PROJECT>" checkbox + "Finish"
##
## Single-instance: a named mutex blocks a second copy of the installer
## from running in parallel.
##
## Install location defaults to %LOCALAPPDATA%\Programs\<PROJECT>
## (the Slack / Discord / VSCode / GitHub Desktop convention) — no
## admin required, the in-app auto-updater can swap the binary
## without UAC.
##
## Installed binary is named <PROJECT>.exe (no version suffix) so
## os.Executable() in the auto-updater always resolves to the same
## canonical path regardless of which version is running.
####
Unicode true

# Overrides applied BEFORE wails_tools.nsh so it doesn't re-set them
# from the wails.json defaults.
!define PRODUCT_EXECUTABLE "<PROJECT>.exe"
!define UNINST_KEY_NAME    "<PROJECT>"

!include "wails_tools.nsh"

VIProductVersion "${INFO_PRODUCTVERSION}.0"
VIFileVersion    "${INFO_PRODUCTVERSION}.0"

VIAddVersionKey "CompanyName"     "${INFO_COMPANYNAME}"
VIAddVersionKey "FileDescription" "${INFO_PRODUCTNAME} Installer"
VIAddVersionKey "ProductVersion"  "${INFO_PRODUCTVERSION}"
VIAddVersionKey "FileVersion"     "${INFO_PRODUCTVERSION}"
VIAddVersionKey "LegalCopyright"  "${INFO_COPYRIGHT}"
VIAddVersionKey "ProductName"     "${INFO_PRODUCTNAME}"

ManifestDPIAware true

!include "MUI.nsh"

!define MUI_ICON   "..\icon.ico"
!define MUI_UNICON "..\icon.ico"
!define MUI_FINISHPAGE_NOAUTOCLOSE
!define MUI_ABORTWARNING

# Branded MUI bitmaps — generated by scripts/release-desktop.sh from
# icon.ico if they don't exist. header.bmp (150x57) sits upper-right
# of every page; welcome.bmp (164x314) is the Welcome+Finish banner.
!define MUI_HEADERIMAGE
!define MUI_HEADERIMAGE_BITMAP            "header.bmp"
!define MUI_HEADERIMAGE_UNBITMAP          "header.bmp"
!define MUI_HEADERIMAGE_RIGHT
!define MUI_WELCOMEFINISHPAGE_BITMAP      "welcome.bmp"
!define MUI_UNWELCOMEFINISHPAGE_BITMAP    "welcome.bmp"

# Welcome page text overrides — these MUST be defined before
# MUI_PAGE_WELCOME is inserted.
!define MUI_WELCOMEPAGE_TITLE   "Welcome to the <PROJECT> Setup Wizard"
!define MUI_WELCOMEPAGE_TEXT    "This will install <PROJECT> v${INFO_PRODUCTVERSION} on your computer.$\r$\n$\r$\nClick Next to continue, or Cancel to exit the wizard."

# Directory page — surface the install location front and centre.
!define MUI_DIRECTORYPAGE_TEXT_TOP "Setup will install <PROJECT> in the folder below. To install in a different folder, click Browse and select another folder. Click Install to start the installation."
!define MUI_DIRECTORYPAGE_TEXT_DESTINATION "Install location"

# Finish page run-on-exit option.
!define MUI_FINISHPAGE_RUN      "$INSTDIR\${PRODUCT_EXECUTABLE}"
!define MUI_FINISHPAGE_RUN_TEXT "Launch <PROJECT> now"

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

!insertmacro MUI_LANGUAGE "English"

# Install WebView2 from the Microsoft Evergreen Standalone Installer
# (~125 MB) that we bundle inside the NSIS. Replaces wails.webview2runtime
# (the 1.8 MB online bootstrapper that requires internet to fetch the
# actual runtime at install time).
#
# The standalone installer file must be staged at
# build\windows\installer\webview2\MicrosoftEdgeWebView2RuntimeInstaller.exe
# before running wails build. scripts/release-desktop.sh downloads it
# once on demand and caches it across releases.
!macro grit.webview2offline
    # Bail if WebView2 is already installed system-wide.
    ReadRegStr $0 HKLM "SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}" "pv"
    StrCmp $0 "" 0 webview2_already_installed
    ReadRegStr $0 HKLM "SOFTWARE\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}" "pv"
    StrCmp $0 "" 0 webview2_already_installed
    ReadRegStr $0 HKCU "Software\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}" "pv"
    StrCmp $0 "" 0 webview2_already_installed

    DetailPrint "Installing Microsoft Edge WebView2 Runtime (offline)..."
    CreateDirectory "$pluginsdir\wv2offline"
    SetOutPath "$pluginsdir\wv2offline"
    File "webview2\MicrosoftEdgeWebView2RuntimeInstaller.exe"
    ExecWait '"$pluginsdir\wv2offline\MicrosoftEdgeWebView2RuntimeInstaller.exe" /silent /install' $0
    DetailPrint "WebView2 install exited with code $0"
    Goto webview2_done

    webview2_already_installed:
        DetailPrint "WebView2 already installed — skipping."

    webview2_done:
!macroend

Function .onInit
    !insertmacro wails.checkArchitecture

    # Single-instance check — only the literal ERROR_ALREADY_EXISTS (183).
    # Using a per-user name (no "Global\") avoids false positives across
    # user sessions on the same Windows install.
    System::Call 'kernel32::CreateMutex(p 0, i 0, t "${INFO_PRODUCTNAME}_Installer") p .r0'
    System::Call 'kernel32::GetLastError() i .r1'
    IntCmp $1 183 0 +3 +3
        MessageBox MB_OK|MB_ICONEXCLAMATION "${INFO_PRODUCTNAME} installer is already running."
        Abort
FunctionEnd

Section
    !insertmacro wails.setShellContext

    # Install the offline WebView2 runtime bundled in this installer.
    !insertmacro grit.webview2offline

    !insertmacro wails.files

    CreateShortcut "$SMPROGRAMS\${INFO_PRODUCTNAME}.lnk" "$INSTDIR\${PRODUCT_EXECUTABLE}"
    CreateShortCut "$DESKTOP\${INFO_PRODUCTNAME}.lnk" "$INSTDIR\${PRODUCT_EXECUTABLE}"

    !insertmacro wails.writeUninstaller
SectionEnd

Section "uninstall"
    !insertmacro wails.setShellContext

    RMDir /r "$AppData\${PRODUCT_EXECUTABLE}"
    RMDir /r $INSTDIR
    Delete "$SMPROGRAMS\${INFO_PRODUCTNAME}.lnk"
    Delete "$DESKTOP\${INFO_PRODUCTNAME}.lnk"

    !insertmacro wails.deleteUninstaller
SectionEnd
`
	return strings.ReplaceAll(tpl, "<PROJECT>", opts.ProjectName)
}

/* ─── NSIS: slim installer ────────────────────────────────────────── */

func desktopNSISlim(opts DesktopOptions) string {
	tpl := `####
## <PROJECT> NSIS installer — SLIM variant
##
## Uses the Wails-shipped wails.webview2runtime macro, which downloads
## the WebView2 runtime from Microsoft at install time (the 1.8 MB
## bootstrapper). Result: a ~22 MB installer instead of ~150 MB. Use
## this variant for distribution to users who have internet during
## install — your support tickets will thank you.
####
Unicode true

!define PRODUCT_EXECUTABLE "<PROJECT>.exe"
!define UNINST_KEY_NAME    "<PROJECT>"

!include "wails_tools.nsh"

VIProductVersion "${INFO_PRODUCTVERSION}.0"
VIFileVersion    "${INFO_PRODUCTVERSION}.0"

VIAddVersionKey "CompanyName"     "${INFO_COMPANYNAME}"
VIAddVersionKey "FileDescription" "${INFO_PRODUCTNAME} Installer (Slim)"
VIAddVersionKey "ProductVersion"  "${INFO_PRODUCTVERSION}"
VIAddVersionKey "FileVersion"     "${INFO_PRODUCTVERSION}"
VIAddVersionKey "LegalCopyright"  "${INFO_COPYRIGHT}"
VIAddVersionKey "ProductName"     "${INFO_PRODUCTNAME}"

ManifestDPIAware true

!include "MUI.nsh"

!define MUI_ICON   "..\icon.ico"
!define MUI_UNICON "..\icon.ico"
!define MUI_FINISHPAGE_NOAUTOCLOSE
!define MUI_ABORTWARNING

!define MUI_HEADERIMAGE
!define MUI_HEADERIMAGE_BITMAP            "header.bmp"
!define MUI_HEADERIMAGE_UNBITMAP          "header.bmp"
!define MUI_HEADERIMAGE_RIGHT
!define MUI_WELCOMEFINISHPAGE_BITMAP      "welcome.bmp"
!define MUI_UNWELCOMEFINISHPAGE_BITMAP    "welcome.bmp"

!define MUI_WELCOMEPAGE_TITLE   "Welcome to the <PROJECT> Setup Wizard (Slim)"
!define MUI_WELCOMEPAGE_TEXT    "This is the SLIM installer for <PROJECT> v${INFO_PRODUCTVERSION}.$\r$\n$\r$\nWebView2 will be downloaded at install time — make sure you have an internet connection.$\r$\n$\r$\nClick Next to continue."

!define MUI_DIRECTORYPAGE_TEXT_TOP "Setup will install <PROJECT> in the folder below."
!define MUI_DIRECTORYPAGE_TEXT_DESTINATION "Install location"

!define MUI_FINISHPAGE_RUN      "$INSTDIR\${PRODUCT_EXECUTABLE}"
!define MUI_FINISHPAGE_RUN_TEXT "Launch <PROJECT> now"

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

!insertmacro MUI_LANGUAGE "English"

Function .onInit
    !insertmacro wails.checkArchitecture

    System::Call 'kernel32::CreateMutex(p 0, i 0, t "${INFO_PRODUCTNAME}_Installer_Slim") p .r0'
    System::Call 'kernel32::GetLastError() i .r1'
    IntCmp $1 183 0 +3 +3
        MessageBox MB_OK|MB_ICONEXCLAMATION "${INFO_PRODUCTNAME} installer is already running."
        Abort
FunctionEnd

Section
    !insertmacro wails.setShellContext

    # Online bootstrapper — ~1.8 MB. Downloads the actual runtime from
    # Microsoft at install time. Wails ships this macro by default.
    !insertmacro wails.webview2runtime

    !insertmacro wails.files

    CreateShortcut "$SMPROGRAMS\${INFO_PRODUCTNAME}.lnk" "$INSTDIR\${PRODUCT_EXECUTABLE}"
    CreateShortCut "$DESKTOP\${INFO_PRODUCTNAME}.lnk" "$INSTDIR\${PRODUCT_EXECUTABLE}"

    !insertmacro wails.writeUninstaller
SectionEnd

Section "uninstall"
    !insertmacro wails.setShellContext

    RMDir /r "$AppData\${PRODUCT_EXECUTABLE}"
    RMDir /r $INSTDIR
    Delete "$SMPROGRAMS\${INFO_PRODUCTNAME}.lnk"
    Delete "$DESKTOP\${INFO_PRODUCTNAME}.lnk"

    !insertmacro wails.deleteUninstaller
SectionEnd
`
	return strings.ReplaceAll(tpl, "<PROJECT>", opts.ProjectName)
}

/* ─── .gitignore for the installer dir ────────────────────────────── */

func desktopInstallerGitignore() string {
	return `# WebView2 offline runtime (~125 MB). Downloaded by the release
# script on demand — too big to commit.
webview2/*.exe

# Generated branded bitmaps. The release script regenerates them
# from icon.ico every release.
header.bmp
welcome.bmp

# Local build artefacts.
tmp/
*.tmp
`
}

/* ─── README for the installer dir ────────────────────────────────── */

func desktopInstallerReadme(opts DesktopOptions) string {
	return fmt.Sprintf(`# Windows installer

Two NSIS templates ship in this directory:

| File | Output | Size | When to use |
|---|---|---|---|
| project.nsi | %s-Setup-v%s.exe | ~150 MB | Bundles the WebView2 runtime — works offline / behind restrictive firewalls. |
| project-slim.nsi | %s-Setup-Slim-v%s.exe | ~22 MB | Downloads WebView2 at install time. Smaller, but needs internet. |

Both are produced by ` + "`scripts/release-desktop.sh`" + `. You should not need to invoke ` + "`makensis`" + ` by hand.

## Branded look (header.bmp + welcome.bmp)

The release script regenerates both bitmaps from ` + "`../icon.ico`" + ` every build — no design work required. Override by replacing this directory's ` + "`icon.ico`" + `; the bitmaps fall in line on the next release.

## WebView2 offline runtime

The full installer bundles ` + "`webview2/MicrosoftEdgeWebView2RuntimeInstaller.exe`" + ` (~125 MB, the Microsoft Edge WebView2 Evergreen Standalone). The release script downloads it once and caches it; you don't commit the binary.

## Code signing (recommended, optional)

A signed .exe skips Windows SmartScreen. A code-signing cert is ~$200/year and pays for itself the first time an enterprise customer doesn't open a support ticket. See ` + "`/docs/desktop/auto-update#code-signing`" + ` for the signtool.exe wiring.
`, opts.ProjectName, "0.1.0", opts.ProjectName, "0.1.0")
}

/* ─── Release script ──────────────────────────────────────────────── */

func desktopReleaseScript(opts DesktopOptions) string {
	tpl := `#!/usr/bin/env bash
# scripts/release-desktop.sh — one-shot release pipeline.
#
# Usage:
#     scripts/release-desktop.sh 1.2.3
#
# What it does:
#     1. Bumps wails.json's productVersion + outputfilename
#     2. Bumps version.go's AppVersion constant
#     3. (Re)generates branded NSIS bitmaps from icon.ico
#     4. Downloads + caches the offline WebView2 runtime
#     5. Runs 'wails build -nsis' (produces raw .exe + full installer)
#     6. Runs makensis on project-slim.nsi (produces slim installer)
#     7. Tags vX.Y.Z, pushes the tag
#     8. 'gh release create' uploads all four assets
#
# Expects to be run from project root.
# Requires: bash, jq, wails, makensis, gh, powershell (Windows).

set -euo pipefail

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <version>     # e.g. $0 1.2.3"
    exit 1
fi

VERSION="$1"
PROJECT="<PROJECT>"
TAG="v${VERSION}"

echo ">> Releasing ${PROJECT} ${TAG}"

# ─── 1. Bump wails.json ──────────────────────────────────────────────
echo ">> Bumping wails.json productVersion + outputfilename"
python3 - <<PYBUMP
import json
with open("wails.json", "r", encoding="utf-8") as f:
    data = json.load(f)
data["info"]["productVersion"] = "${VERSION}"
data["outputfilename"] = "${PROJECT}-v${VERSION}"
with open("wails.json", "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2)
    f.write("\n")
PYBUMP

# ─── 2. Bump version.go ──────────────────────────────────────────────
echo ">> Bumping version.go AppVersion"
sed -i.bak -E 's/(AppVersion = ")[^"]+(")/\1'"${VERSION}"'\2/' version.go
rm -f version.go.bak

# ─── 3. Generate branded bitmaps from icon.ico ───────────────────────
echo ">> Generating NSIS bitmaps from icon.ico"
ICON="build/windows/icon.ico"
INSTDIR="build/windows/installer"
if [ ! -f "${ICON}" ]; then
    echo "!! ${ICON} missing — wails generates it on first build. Run 'wails build' once."
    exit 1
fi
powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "
Add-Type -AssemblyName System.Drawing
function Save-Bmp(\$icon, \$w, \$h, \$out) {
    \$bmp = New-Object System.Drawing.Bitmap \$w, \$h
    \$g = [System.Drawing.Graphics]::FromImage(\$bmp)
    \$g.Clear([System.Drawing.Color]::White)
    \$src = [System.Drawing.Icon]::ExtractAssociatedIcon('${ICON}')
    \$g.DrawIcon(\$src, [int]((\$w - \$src.Width) / 2), [int]((\$h - \$src.Height) / 2))
    \$bmp.Save(\$out, [System.Drawing.Imaging.ImageFormat]::Bmp)
    \$g.Dispose()
    \$bmp.Dispose()
}
Save-Bmp '${ICON}' 150 57 '${INSTDIR}/header.bmp'
Save-Bmp '${ICON}' 164 314 '${INSTDIR}/welcome.bmp'
"

# ─── 4. Cache WebView2 offline runtime ───────────────────────────────
WEBVIEW2_DIR="${INSTDIR}/webview2"
WEBVIEW2_BIN="${WEBVIEW2_DIR}/MicrosoftEdgeWebView2RuntimeInstaller.exe"
mkdir -p "${WEBVIEW2_DIR}"
if [ ! -f "${WEBVIEW2_BIN}" ]; then
    echo ">> Downloading WebView2 offline runtime (~125 MB) — one-time"
    # Microsoft's Evergreen Standalone Installer (x64). Stable URL.
    curl -L "https://go.microsoft.com/fwlink/?linkid=2124701" \
        -o "${WEBVIEW2_BIN}.tmp"
    mv "${WEBVIEW2_BIN}.tmp" "${WEBVIEW2_BIN}"
fi

# ─── 5. wails build -nsis (raw .exe + full installer) ────────────────
echo ">> wails build -nsis -platform windows/amd64"
wails build -nsis -platform windows/amd64 -trimpath -ldflags '-s -w'

BIN_DIR="build/bin"
RAW_EXE="${BIN_DIR}/${PROJECT}-v${VERSION}.exe"
FULL_SETUP="${BIN_DIR}/${PROJECT}-v${VERSION}-amd64-installer.exe"
TARGET_FULL="${BIN_DIR}/${PROJECT}-Setup-v${VERSION}.exe"
if [ -f "${FULL_SETUP}" ]; then
    mv "${FULL_SETUP}" "${TARGET_FULL}"
fi

# ─── 6. Slim installer ───────────────────────────────────────────────
echo ">> makensis: slim installer"
SLIM_TARGET="${BIN_DIR}/${PROJECT}-Setup-Slim-v${VERSION}.exe"
makensis \
    "-DARG_WAILS_AMD64_BINARY=$(pwd)/${RAW_EXE}" \
    "-DARG_OUT_FILE=$(pwd)/${SLIM_TARGET}" \
    "${INSTDIR}/project-slim.nsi"

# ─── 7. Tag + push ───────────────────────────────────────────────────
echo ">> git tag ${TAG}"
git add wails.json version.go
git commit -m "chore: release ${TAG}" || echo "nothing to commit"
git tag -a "${TAG}" -m "Release ${TAG}"
git push origin main
git push origin "${TAG}"

# ─── 8. GitHub release ───────────────────────────────────────────────
echo ">> gh release create ${TAG}"
gh release create "${TAG}" \
    --title "${TAG}" \
    --generate-notes \
    "${RAW_EXE}" \
    "${TARGET_FULL}" \
    "${SLIM_TARGET}"

echo ">> Done — ${TAG} published with raw .exe + full installer + slim installer."
`
	return strings.ReplaceAll(tpl, "<PROJECT>", opts.ProjectName)
}
