package scaffold

import (
	"os"
	"path/filepath"
	"testing"
)

// One-shot extractor, run by hand to move a batch of templates out of Go string
// literals and into files:
//
//	go test ./internal/scaffold/ -run TestExtractTemplates -extract
//
// It is skipped without the flag, so an ordinary test run never writes to the
// repository.
//
// Not one-shot: the next directory moves the same way, by adding its functions
// to the map below and running this once. Re-running it over a batch that has
// already moved is a no-op, because those functions now read the files it would
// write.
//
// Two things to get right, both learned the hard way on this batch. Extract
// before rewriting the functions, or the extractor reads what it just wrote.
// And never put the output through gofmt: the scaffolder formats on the way
// out, and formatting here means substituting something for {{MODULE}}, which
// sorts to a different place in the import block than a real module path.
var extract = os.Getenv("GRIT_EXTRACT_TEMPLATES") != ""

// handlerTemplates is the batch being moved: everything written into a
// generated project's internal/handlers.
var handlerTemplates = map[string]func() string{
	"api/handlers/scale.go":                   apiScaleHandlerGo,
	"api/handlers/session.go":                 apiSessionHandlerGo,
	"api/handlers/sso.go":                     apiSSOHandlerGo,
	"api/handlers/saml.go":                    apiSAMLHandlerGo,
	"api/handlers/auth.go":                    apiAuthHandlerGo,
	"api/handlers/auth_password_reset.go":     apiAuthPasswordResetGo,
	"api/handlers/auth_email_verification.go": apiAuthEmailVerificationGo,
	"api/handlers/auth_oauth.go":              apiAuthOAuthGo,
	"api/handlers/auth_lockout.go":            apiAuthLockoutGo,
	"api/handlers/user.go":                    apiUserHandlerGo,
	"api/handlers/realtime.go":                apiRealtimeHandlerGo,
	"api/handlers/realtime_test.go":           apiRealtimeHandlerTestGo,
	"api/handlers/realtime_greeting_test.go":  apiRealtimeGreetingTestGo,
	"api/handlers/realtime_channels_test.go":  apiRealtimeChannelsHandlerTestGo,
	"api/handlers/settings.go":                apiSettingsHandlerGo,
	"api/handlers/sync.go":                    apiSyncHandlerGo,
	"api/handlers/activity.go":                apiActivityHandlerGo,
	"api/handlers/flags.go":                   apiFlagsHandlerGo,
	"api/handlers/user_activity.go":           userActivityHandlerGo,
	"api/handlers/ocsf.go":                    apiOCSFHandlerGo,
	"api/handlers/access_review.go":           apiAccessReviewHandlerGo,
	"api/handlers/gdpr.go":                    apiGDPRHandlerGo,
	"api/handlers/ticket.go":                  ticketHandlerGo,
	"api/handlers/import_job.go":              importJobHandlerGo,
	"api/handlers/auth_test.go":               apiAuthTestGo,
	"api/handlers/sso_test.go":                apiSSOTestGo,
	"api/handlers/saml_test.go":               apiSAMLTestGo,
	"api/handlers/user_test.go":               apiUserTestGo,
	"api/handlers/bench_test.go":              apiBenchTestGo,

	// The auth service, because the repair that brings an older project up to
	// the current handler needs its query methods as a block it can append.
	"api/services/auth.go": apiAuthServiceGo,

	// The roles API: the handler whose queries are moving onto a service, and
	// the test that goes with it.
	"api/handlers/role.go":      roleHandlerGo,
	"api/handlers/role_test.go": roleHandlerTestGo,

	// Two-factor: 870 lines and thirty-five queries, the largest of the
	// framework's handlers.
	"api/handlers/totp.go": totpHandlerGo,
}

func TestExtractTemplates(t *testing.T) {
	if !extract {
		t.Skip("set GRIT_EXTRACT_TEMPLATES=1 to write the template files")
	}
	for name, fn := range handlerTemplates {
		path := filepath.Join("templates", name+".tmpl")
		// A template that already exists is left alone, and this is not a
		// nicety. Its function reads it through tmpl, which strips the repair
		// markers on the way out, so writing that back deletes every marker in
		// the file: the next scaffold panicked at init, having lost the blocks
		// four repairs take their text from. The comment above said re-running
		// was a no-op. It was, for one release.
		if _, err := os.Stat(path); err == nil {
			t.Logf("kept %s", path)
			continue
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		// One trailing newline, because a file has one and the literal did
		// not. tmpl() trims it back off so the generated bytes do not change.
		if err := os.WriteFile(path, []byte(fn()+"\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("wrote %s", path)
	}
}
