package generate

import (
	"fmt"
	"strings"
)

// PerfOptions configures a generated k6 load test.
type PerfOptions struct {
	// Resource, if set, adds a scenario that lists that resource's collection
	// endpoint (e.g. "Blog" → GET /api/blogs). Empty = health + auth only.
	Resource string
	// VUs is the peak number of virtual users (concurrent clients).
	VUs int
	// Duration is how long to hold at peak (k6 stage duration, e.g. "30s", "2m").
	Duration string
	// BaseURL is the default target; overridable at run time via BASE_URL.
	BaseURL string
}

func (o *PerfOptions) applyDefaults() {
	if o.VUs <= 0 {
		o.VUs = 20
	}
	if strings.TrimSpace(o.Duration) == "" {
		o.Duration = "30s"
	}
	if strings.TrimSpace(o.BaseURL) == "" {
		o.BaseURL = "http://localhost:8080"
	}
}

// GeneratePerf writes a k6 load test (perf/load.js) and a runbook (perf/README.md)
// into the current project. The script follows Grit's API conventions: it
// registers and logs in a user in setup() to obtain a bearer token, then every
// virtual user hammers the health check, the authenticated profile read, and —
// if a resource is named — that resource's list endpoint. Thresholds fail the
// run if the error rate or p95 latency crosses a line, so it doubles as a
// regression gate in CI, not just an ad-hoc benchmark.
func GeneratePerf(opts PerfOptions) error {
	opts.applyDefaults()

	if err := writeFileWithDirs("perf/load.js", perfScript(opts)); err != nil {
		return fmt.Errorf("writing perf/load.js: %w", err)
	}
	if err := writeFileWithDirs("perf/README.md", perfReadme(opts)); err != nil {
		return fmt.Errorf("writing perf/README.md: %w", err)
	}
	return nil
}

// perfScript renders the k6 script. It is exported-for-test via BuildPerfScript
// so the generator's output can be asserted without touching the filesystem.
func perfScript(opts PerfOptions) string {
	opts.applyDefaults()

	resourceScenario := ""
	if opts.Resource != "" {
		plural := Pluralize(strings.ToLower(opts.Resource))
		lower := strings.ToLower(opts.Resource)
		resourceScenario = fmt.Sprintf(`
  // 3. %s collection (authenticated) — the CRUD read path under load.
  const list = http.get(`+"`${BASE}/api/%s`"+`, authParams);
  check(list, { '%s list is 200': (r) => r.status === 200 });
`, opts.Resource, plural, lower)
	}

	return fmt.Sprintf(`// k6 load test for this Grit API. Generated by `+"`grit generate perf`"+`.
//
// Run it:   k6 run perf/load.js
// Override: BASE_URL=https://staging.example.com k6 run perf/load.js
//
// The thresholds below fail the run (non-zero exit) if the error rate or p95
// latency regresses, so this works as a CI gate as well as an ad-hoc benchmark.
import http from 'k6/http';
import { check, sleep } from 'k6';

const BASE = __ENV.BASE_URL || '%s';

export const options = {
  // Ramp to %d virtual users, hold for %s, then ramp down.
  stages: [
    { duration: '10s', target: %d },
    { duration: '%s', target: %d },
    { duration: '10s', target: 0 },
  ],
  thresholds: {
    http_req_failed: ['rate<0.01'],   // fewer than 1%% of requests may fail
    http_req_duration: ['p(95)<500'], // 95%% of requests must finish under 500ms
  },
};

// setup() runs once before the load. It registers a throwaway user and logs in,
// returning a bearer token every virtual user shares — Grit accepts
// "Authorization: Bearer <token>", which sidesteps cookie jars and CSRF.
export function setup() {
  const email = `+"`perf+${Date.now()}@loadtest.local`"+`;
  const password = 'Password123!';
  const json = { headers: { 'Content-Type': 'application/json' } };

  http.post(`+"`${BASE}/api/auth/register`"+`, JSON.stringify({
    first_name: 'Load', last_name: 'Test', email, password,
  }), json);

  const res = http.post(`+"`${BASE}/api/auth/login`"+`, JSON.stringify({ email, password }), json);
  const token = res.json('data.tokens.access_token');
  if (!token) {
    throw new Error('setup: could not obtain an access token (login returned ' + res.status + ')');
  }
  return { token };
}

export default function (data) {
  const authParams = { headers: { Authorization: `+"`Bearer ${data.token}`"+` } };

  // 1. Health check (unauthenticated) — the cheapest liveness path.
  const health = http.get(`+"`${BASE}/api/health`"+`);
  check(health, { 'health is 200': (r) => r.status === 200 });

  // 2. Authenticated profile read — exercises the auth middleware per request.
  const profile = http.get(`+"`${BASE}/api/profile`"+`, authParams);
  check(profile, { 'profile is 200': (r) => r.status === 200 });
%s
  sleep(1);
}
`, opts.BaseURL, opts.VUs, opts.Duration, opts.VUs, opts.Duration, opts.VUs, resourceScenario)
}

// BuildPerfScript exposes the rendered script for tests.
func BuildPerfScript(opts PerfOptions) string { return perfScript(opts) }

func perfReadme(opts PerfOptions) string {
	opts.applyDefaults()

	resourceLine := ""
	if opts.Resource != "" {
		resourceLine = fmt.Sprintf("- `GET /api/%s`: %s collection under load\n",
			Pluralize(strings.ToLower(opts.Resource)), opts.Resource)
	}

	return fmt.Sprintf("# Load testing\n\n"+
		"A [k6](https://k6.io) load test lives in `perf/load.js`, generated by "+
		"`grit generate perf`.\n\n"+
		"## Run it\n\n"+
		"```bash\n"+
		"# install k6: https://grafana.com/docs/k6/latest/set-up/install-k6/\n"+
		"k6 run perf/load.js\n\n"+
		"# against another environment\n"+
		"BASE_URL=https://staging.example.com k6 run perf/load.js\n"+
		"```\n\n"+
		"## What it hits\n\n"+
		"Each virtual user, per iteration:\n\n"+
		"- `GET /api/health` — liveness\n"+
		"- `GET /api/profile` — an authenticated read (a bearer token is minted once in `setup()`)\n"+
		resourceLine+
		"\n## Load profile\n\n"+
		"Ramps to **%d virtual users**, holds for **%s**, then ramps down. Tune the "+
		"stages in `perf/load.js`.\n\n"+
		"## Pass/fail\n\n"+
		"The run exits non-zero if either threshold is breached, so it can gate a "+
		"deploy:\n\n"+
		"- `http_req_failed` — error rate must stay **under 1%%**\n"+
		"- `http_req_duration` — **p95 under 500ms**\n",
		opts.VUs, opts.Duration)
}
